/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos;

import entidades.articulo.Articulo;
import entidades.articulo.SubCategoria;
import entidades.articulo.UnidadMedida;
import facade.ArticuloFacade;
import facade.SubCategoriaFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import javax.swing.JOptionPane;
import vista.categorias.DiagSubCategoria;

/**
 *
 * @author hugo
 */
public class DiagArticulo extends javax.swing.JDialog {

    private Articulo articulo;
    private String tipoOperacion;

    /**
     * Creates new form DiagArticulo
     */
    public DiagArticulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    public DiagArticulo(java.awt.Frame parent, boolean modal, String tipoOperacion, Articulo articulo) {
        super(parent, modal);
        initComponents();
        this.articulo = articulo;
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfDescripcionRed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfCodigoBarra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cboSubCategoria = new javax.swing.JComboBox();
        btnNuevaSubcategoria = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cboUnidadDeMedida = new javax.swing.JComboBox();
        btnNuevaUnidadMedida = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jLabel1.text")); // NOI18N

        tfDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.tfDescripcion.text")); // NOI18N

        tfDescripcionRed.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.tfDescripcionRed.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jLabel3.text")); // NOI18N

        tfCodigoBarra.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.tfCodigoBarra.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jLabel4.text")); // NOI18N

        cboSubCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNuevaSubcategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnNuevaSubcategoria.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.btnNuevaSubcategoria.text")); // NOI18N
        btnNuevaSubcategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaSubcategoriaActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.jLabel5.text")); // NOI18N

        cboUnidadDeMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNuevaUnidadMedida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnNuevaUnidadMedida.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.btnNuevaUnidadMedida.text")); // NOI18N
        btnNuevaUnidadMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaUnidadMedidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cboUnidadDeMedida, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfCodigoBarra, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboSubCategoria, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNuevaSubcategoria)
                                .addComponent(btnNuevaUnidadMedida))
                            .addGap(42, 42, 42))
                        .addComponent(tfDescripcionRed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDescripcionRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboUnidadDeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevaSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(btnNuevaUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, Short.MAX_VALUE))
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnAceptar.setText(org.openide.util.NbBundle.getMessage(DiagArticulo.class, "DiagArticulo.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnAceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaSubcategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaSubcategoriaActionPerformed
        agregarNuevaSubcategoria();
        Comunes.cargarJCombo(cboSubCategoria, SubCategoriaFacade.getInstance().getTodos());
    }//GEN-LAST:event_btnNuevaSubcategoriaActionPerformed

    private void btnNuevaUnidadMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaUnidadMedidaActionPerformed
        agregarUnidadMedida();
        Comunes.cargarJCombo(cboUnidadDeMedida, UnidadMedidaFacade.getInstance().getTodos());
    }//GEN-LAST:event_btnNuevaUnidadMedidaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagArticulo dialog = new DiagArticulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnNuevaSubcategoria;
    private javax.swing.JButton btnNuevaUnidadMedida;
    private javax.swing.JComboBox cboSubCategoria;
    private javax.swing.JComboBox cboUnidadDeMedida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCodigoBarra;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfDescripcionRed;
    // End of variables declaration//GEN-END:variables

    private void agregarNuevaSubcategoria() {
        DiagSubCategoria diagSubCategoria = new DiagSubCategoria(null, true, "Alta");
        diagSubCategoria.setLocation(Comunes.centrarDialog(diagSubCategoria));
        diagSubCategoria.setVisible(true);
    }

    private void inicializarComponentes() {
        Comunes.limitarTextField(tfDescripcionRed, 30);
        this.setTitle("Articulo");
        Comunes.cargarJCombo(cboSubCategoria, SubCategoriaFacade.getInstance().getTodos());
        Comunes.cargarJCombo(cboUnidadDeMedida, UnidadMedidaFacade.getInstance().getTodos());
        if (tipoOperacion.equals("Modificación")) {
            cargarDatosArticulo();
        }
    }

    private void aceptar() {
        if (tipoOperacion.equals("Alta")) {
            if (validarArticulo()) {
                articulo = new Articulo();
                articulo.setCodigoBarra(tfCodigoBarra.getText().toUpperCase());
                articulo.setDescripcion(tfDescripcion.getText().toUpperCase());
                articulo.setDescripcionReducida(tfDescripcionRed.getText().toUpperCase());
                articulo.setSubCategoria((SubCategoria) cboSubCategoria.getSelectedItem());
                articulo.setUnidadMedida((UnidadMedida) cboUnidadDeMedida.getSelectedItem());
                ArticuloFacade.getInstance().alta(articulo);
                JOptionPane.showMessageDialog(this, "Articulo agregado!");
                this.dispose();

            }

        } else if (tipoOperacion.equals("Modificación")) {
            if (validarArticulo()) {
                articulo.setCodigoBarra(tfCodigoBarra.getText().toUpperCase());
                articulo.setDescripcion(tfDescripcion.getText().toUpperCase());
                articulo.setDescripcionReducida(tfDescripcionRed.getText());
                articulo.setSubCategoria((SubCategoria) cboSubCategoria.getSelectedItem());
                articulo.setUnidadMedida((UnidadMedida) cboUnidadDeMedida.getSelectedItem());
                ArticuloFacade.getInstance().modificar(articulo);
                JOptionPane.showMessageDialog(this, "Articulo modificado!");
                this.dispose();

            }
        }

    }

    private void cargarDatosArticulo() {
        try {
            tfDescripcion.setText(articulo.getDescripcion());
        } catch (Exception e) {

        }
        try {
            tfDescripcionRed.setText(articulo.getDescripcionReducida());
        } catch (Exception e) {

        }
        try {
            tfCodigoBarra.setText(articulo.getCodigoBarra());
        } catch (Exception e) {

        }
        try {
            cboSubCategoria.setSelectedItem(articulo.getSubCategoria());
        } catch (Exception e) {

        }
        try {
            cboUnidadDeMedida.setSelectedItem(articulo.getUnidadMedida());
        } catch (Exception e) {

        }
    }

    private boolean validarArticulo() {
        //boolean flag=Boolean.TRUE;
        if (tfDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El articulo debe tener nombre", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfDescripcionRed.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El articulo debe tener Descripcion", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfCodigoBarra.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El articulo debe tener Codigo", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tipoOperacion.equals("Alta")) {
            if (ArticuloFacade.getInstance().buscarCodigoBarra(tfCodigoBarra.getText())) {
                JOptionPane.showMessageDialog(this, "El codigo de Articulo ya Existe", "Mensaje", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return true;
    }

    private void cargarDatos() {

    }

    private void agregarUnidadMedida() {
        DiagUnidadMedida diagUnidadMedida = new DiagUnidadMedida(null, true, "Alta");
        diagUnidadMedida.setLocationRelativeTo(null);
        diagUnidadMedida.setVisible(true);
    }

    private void eliminarUnidadMedida() {
        int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar Unidad De Medida?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                UnidadMedidaFacade.getInstance().eliminar(((UnidadMedida) cboUnidadDeMedida.getSelectedItem()).getId());
                JOptionPane.showMessageDialog(null, "Unidad de Medida eliminada");
                Comunes.cargarJCombo(cboUnidadDeMedida, UnidadMedidaFacade.getInstance().getTodos());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar, unidad de medida en uso!");
            }
        }
    }

    private void eliminarSubcategoria() {
        int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar Subcategoria?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if (i == 0) {
            try {
                SubCategoriaFacade.getInstance().eliminar(((SubCategoria) cboSubCategoria.getSelectedItem()).getId());
                JOptionPane.showMessageDialog(null, "Subcategoria eliminada");
                Comunes.cargarJCombo(cboSubCategoria, SubCategoriaFacade.getInstance().getTodos());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "No se puede eliminar, Subcategoria en uso!");
            }
        }
    }
}
