/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.articulos;

import entidades.articulo.Articulo;
import entidades.articulo.Categoria;
import entidades.articulo.SubCategoria;
import entidades.articulo.TipoIva;
import entidades.articulo.UnidadMedida;
import entidades.cliente.Cliente;
import entidades.cliente.Organismo;
import entidades.cliente.Persona;
import facade.ArticuloFacade;
import facade.CategoriaFacade;
import facade.ClienteFacade;
import facade.SubCategoriaFacade;
import facade.TipoIvaFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import includes.ExportarExcel;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.NoResultException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import vista.cliente.*;

/**
 *
 * @author hugo
 */
public class DiagExportarImportarArticulos extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private String tipoOperacion;
    private javax.swing.JTextField jTextField;
    private ModeloTablaNoEditable modeloTablaArticulos;
    private Vector headers = new Vector();
    private Vector data = new Vector();
    private Articulo articulo;

    private SubCategoria subCategoria;
    private Categoria categoria;
    private TipoIva tipoIva;
    private UnidadMedida unidadMedida;

    public DiagExportarImportarArticulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagExportarImportarArticulos(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodDesc = new javax.swing.ButtonGroup();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticulos = new javax.swing.JTable();
        btnExportarArt = new javax.swing.JButton();
        btnImportarArt = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarArticulos.class, "DiagExportarImportarArticulos.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagExportarImportarArticulos.class, "DiagExportarImportarArticulos.jPanel3.border.title"))); // NOI18N

        tblArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Descripcion", "Subcategoria", "Categoria", "Iva", "Porcentaje", "Unidad de Medida", "esPeso", "Medida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblArticulos);

        btnExportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnExportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarArticulos.class, "DiagExportarImportarArticulos.btnExportarArt.text")); // NOI18N
        btnExportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarArtActionPerformed(evt);
            }
        });

        btnImportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnImportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarArticulos.class, "DiagExportarImportarArticulos.btnImportarArt.text")); // NOI18N
        btnImportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarArtActionPerformed(evt);
            }
        });

        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardarCambios.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarArticulos.class, "DiagExportarImportarArticulos.btnGuardarCambios.text")); // NOI18N
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(btnGuardarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnExportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnExportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnImportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnExportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarArtActionPerformed
        Exportar();
    }//GEN-LAST:event_btnExportarArtActionPerformed

    private void btnImportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarArtActionPerformed
        Importar();
    }//GEN-LAST:event_btnImportarArtActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        guardarArticulos();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagExportarImportarArticulos dialog = new DiagExportarImportarArticulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodDesc;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportarArt;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnImportarArt;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticulos;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        subCategoria = new SubCategoria();
        categoria = new Categoria();
        tipoIva = new TipoIva();
        unidadMedida = new UnidadMedida();
        this.setTitle("Exportar/Importar Articulos");
        cargarTablaArticulos(ArticuloFacade.getInstance().getTodosCodigo());

    }

    private void cargarTablaArticulos(List<Articulo> articulos) {
        modeloTablaArticulos = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulos(modeloTablaArticulos);
        configurarTabla(tblArticulos);
        try {
            cargarArticulos(articulos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaArticulos(ModeloTablaNoEditable modeloTablaArticulos) {
        modeloTablaArticulos.addColumn("Id");
        modeloTablaArticulos.addColumn("Codigo");
        modeloTablaArticulos.addColumn("Nombre");
        modeloTablaArticulos.addColumn("Descripcion");
        modeloTablaArticulos.addColumn("Subcategoria");
        modeloTablaArticulos.addColumn("Categoria");
        modeloTablaArticulos.addColumn("Iva");
        modeloTablaArticulos.addColumn("Porcentaje");
        modeloTablaArticulos.addColumn("Unidad de Medida");
        modeloTablaArticulos.addColumn("es Peso");
        modeloTablaArticulos.addColumn("Medida");
        tblArticulos.setModel(modeloTablaArticulos);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarArticulos(List<Articulo> articulos) {
        try {
            modeloTablaArticulos = new ModeloTablaNoEditable();
            cargarEncabezadosTablaArticulos(modeloTablaArticulos);
            for (Articulo articulo : articulos) {
                cargarArticulo(articulo);
            }

            tblArticulos.setModel(modeloTablaArticulos);
            Comunes.setOcultarColumnasJTable(tblArticulos, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagExportarImportarArticulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarArticulo(Articulo articulo) {

        Object[] fila = new Object[11];
        fila[0] = articulo.getId();
        fila[1] = articulo.getCodigoBarra();
        fila[2] = articulo.getDescripcion();
        fila[3] = articulo.getDescripcionReducida();
        fila[4] = articulo.getSubCategoria();
        fila[5] = articulo.getSubCategoria().getCategoria();
        fila[6] = articulo.getSubCategoria().getCategoria().getTipoIva();
        fila[7] = articulo.getSubCategoria().getCategoria().getTipoIva().getPorcentaje();
        fila[8] = articulo.getUnidadMedida();
        fila[9] = articulo.getUnidadMedida().isEsPeso();
        fila[10] = articulo.getUnidadMedida().getMedida();
        modeloTablaArticulos.addRow(fila);
    }

    private void Exportar() {
        new ExportarExcel().crearExcelJtable(tblArticulos, "Listado de Articulos");
    }

    private void Importar() {
        JFileChooser jChooser = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xls");
        jChooser.setFileFilter(filter);
        jChooser.showOpenDialog(this);
        File file = jChooser.getSelectedFile();
        if (file == null || !file.getName().endsWith("xls")) {
            JOptionPane.showMessageDialog(null, "Solo se permiten Archivos .xls.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            leerDatosExcel(file);
            List<Integer> columnasNoEditables = new ArrayList<>();
            columnasNoEditables.add(0);
            columnasNoEditables.add(1);
            columnasNoEditables.add(2);
            columnasNoEditables.add(3);
            columnasNoEditables.add(4);
            columnasNoEditables.add(5);
            columnasNoEditables.add(6);
            columnasNoEditables.add(7);
            columnasNoEditables.add(8);
            columnasNoEditables.add(9);
            columnasNoEditables.add(10);
            ModeloTablaNoEditable model = new ModeloTablaNoEditable(data, headers, columnasNoEditables);
            tblArticulos.setModel(model);
        }
    }

    void leerDatosExcel(File file) {
        Workbook workbook = null;
        try {
            try {
                workbook = Workbook.getWorkbook(file);
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
            Sheet sheet = workbook.getSheet(0);
            headers.clear();
            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                headers.add(cell1.getContents());
            }
            data.clear();
            for (int j = 1; j < sheet.getRows(); j++) {
                Vector d = new Vector();
                for (int i = 0; i < sheet.getColumns(); i++) {
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

    private void guardarArticulos() {
        try {
            for (int i = 0; i < tblArticulos.getRowCount(); i++) {

                if (!ArticuloFacade.getInstance().buscarExistenciaCodigoBarra((String) tblArticulos.getValueAt(i, 1))) {
                    articulo = new Articulo();
                    articulo.setCodigoBarra(tblArticulos.getValueAt(i, 1).toString());
                    articulo.setDescripcion(tblArticulos.getValueAt(i, 2).toString());
                    articulo.setDescripcionReducida(tblArticulos.getValueAt(i, 3).toString());
                    //Subcategoria
                    if (SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticulos.getValueAt(i, 4)) != null) {
                        //si existe la subcategoria en la base de datos
                        subCategoria = SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticulos.getValueAt(i, 4));
                        articulo.setSubCategoria(subCategoria);
                    } else {
                        //Chequeamos que exista la Categoria
                        if (CategoriaFacade.getInstance().buscarPorDescripcionUnico((String) tblArticulos.getValueAt(i, 5)) != null) {
                            //si existe, se la trae y se le setea la categoria a la subCategoria
                            categoria = CategoriaFacade.getInstance().buscarPorDescripcionUnico((String) tblArticulos.getValueAt(i, 5));
                        } else {
                            //Sino existe la categoria se la da de alta y se le setea a la SubCategoria 
                            //tambien hay que ver si existe el iva relacionado sino hay que darle de alta y setearlo tambien
                            categoria.setDescripcion((String) tblArticulos.getValueAt(i, 5));

                            //inicio iva   
                            if (TipoIvaFacade.getInstance().buscarPorDescripcionUnico((String) tblArticulos.getValueAt(i, 6)) != null) {
                                //si existe, se la trae y se le setea el iva a la categoria
                                tipoIva = TipoIvaFacade.getInstance().buscarPorDescripcionUnico((String) tblArticulos.getValueAt(i, 6));
                            } else {
                                //Sino existe la categoria se la da de alta y se le setea a la SubCategoria 
                                //tambien hay que ver si existe el iva relacionado sino hay que darle de alta y setearlo tambien
                                tipoIva.setDescripcion((String) tblArticulos.getValueAt(i, 6));
                                tipoIva.setPorcentaje(new BigDecimal((String) tblArticulos.getValueAt(i, 7)));
                                TipoIvaFacade.getInstance().getInstance().alta(tipoIva);
                            }
                            //fin iva
                            categoria.setTipoIva(tipoIva);
                            CategoriaFacade.getInstance().alta(categoria);
                        }

                        //sino existe la SubCategoria se la da de alta
                        subCategoria.setDescripcion((String) tblArticulos.getValueAt(i, 4));
                        subCategoria.setCategoria(categoria);
                        SubCategoriaFacade.getInstance().alta(subCategoria);
                        articulo.setSubCategoria(subCategoria);

                        System.out.println("llego hasta ");
                        //subCategoria = SubCategoriaFacade.getInstance().buscarPorDescripcion((String) tblArticulos.getValueAt(i, 4));

                    }

                    //Unidad de medida
                    if (UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticulos.getValueAt(i, 8)) != null) {
                        System.out.println("paso 4 if");
                        unidadMedida = UnidadMedidaFacade.getInstance().buscaDescripcion((String) tblArticulos.getValueAt(i, 8));

                    } else {
                        unidadMedida.setDescripcion((String) tblArticulos.getValueAt(i, 8));
                        if (tblArticulos.getValueAt(i, 9).equals("true")) {
                            unidadMedida.setEsPeso(true);
                        } else {
                            unidadMedida.setEsPeso(false);
                        }
                        unidadMedida.setMedida((String) tblArticulos.getValueAt(i, 9));
                        UnidadMedidaFacade.getInstance().alta(unidadMedida);
                    }
                    articulo.setUnidadMedida(unidadMedida);
                    ArticuloFacade.getInstance().alta(articulo);

                    subCategoria = new SubCategoria();
                    categoria = new Categoria();
                    unidadMedida = new UnidadMedida();

                } else {

                }

            }
            JOptionPane.showMessageDialog(null, "Articulos importados Correctamente");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error Al tratar de Importar los datos" + e);
        }

    }

}
