/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.Sucursal;
import entidades.caja.Caja;
import entidades.venta.Venta;
import entidades.venta.VentaArticulo;
import facade.VentaFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author hugo
 */
public class DiagDetalleVenta extends javax.swing.JDialog {

    /**
     * Creates new form DiagDetalleVenta
     */
    private ModeloTablaNoEditable modeloTablaVenta;
    private Caja caja;
    private Sucursal sucursal;
    private ModeloTablaNoEditable modeloTablaDetalle;

    public DiagDetalleVenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagDetalleVenta(java.awt.Frame parent, boolean modal, Caja caja, Sucursal sucursal) {
        super(parent, modal);
        initComponents();
        this.caja = caja;
        this.sucursal = sucursal;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalle = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.jPanel1.border.title"))); // NOI18N

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVentas);
        if (tblVentas.getColumnModel().getColumnCount() > 0) {
            tblVentas.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.tblVentas.columnModel.title0")); // NOI18N
            tblVentas.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.tblVentas.columnModel.title1")); // NOI18N
            tblVentas.getColumnModel().getColumn(2).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.tblVentas.columnModel.title2")); // NOI18N
            tblVentas.getColumnModel().getColumn(3).setHeaderValue(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.tblVentas.columnModel.title3")); // NOI18N
        }

        jButton2.setText(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tblDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblDetalle);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jButton1.setText(org.openide.util.NbBundle.getMessage(DiagDetalleVenta.class, "DiagDetalleVenta.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(328, 328, 328))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarVentasCajaActual(VentaFacade.getInstance().listaVentasSinCobrar(sucursal));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVentasMouseClicked
        mostrarDetalleVenta();
    }//GEN-LAST:event_tblVentasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagDetalleVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagDetalleVenta dialog = new DiagDetalleVenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDetalle;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        cargarVentasCajaActual(VentaFacade.getInstance().listaVentasSinCobrar(sucursal));
    }

    private void cargarVentasCajaActual(List<Venta> listaVentasSinCobrar) {
        modeloTablaVenta = new ModeloTablaNoEditable();
        cargarEncabezadosTablaVenta(modeloTablaVenta);
        configurarTablaVentas(tblVentas);
        try {
            cargarTickets(listaVentasSinCobrar);
        } catch (Exception ex) {
            Logger.getLogger(DiagCobroTicket2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarEncabezadosTablaVenta(ModeloTablaNoEditable modeloTablaVenta) {
        modeloTablaVenta.addColumn("Id");
        modeloTablaVenta.addColumn("Nro Ticket");
        modeloTablaVenta.addColumn("Fecha");
        modeloTablaVenta.addColumn("Cliente");
        modeloTablaVenta.addColumn("Detalle");
        modeloTablaVenta.addColumn("Total");
        tblVentas.setModel(modeloTablaVenta);
    }

    private void configurarTablaVentas(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 15));
    }

    private void cargarTickets(List<Venta> ventas) {
        try {
            modeloTablaVenta = new ModeloTablaNoEditable();
            cargarEncabezadosTablaVenta(modeloTablaVenta);
            ventas.forEach((v) -> {
                cargarticket(v);
            });

            tblVentas.setModel(modeloTablaVenta);
            Comunes.setOcultarColumnasJTable(tblVentas, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagSueldosAdelantos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarticket(Venta venta) {
        Object[] fila = new Object[6];
        fila[0] = venta.getId();

        fila[1] = venta.getNumeroTicket();
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        try {
            fila[2] = formats.format(venta.getFecha());
        } catch (Exception e) {

        }

        fila[3] = venta.getCliente();
        // CARGAMOS LOS ARTICULOS EN UN STRING PARA MOSTRARLOS
        StringBuilder stringArticulos = new StringBuilder();
        for (VentaArticulo a : venta.getVentasArticulos()) {
            stringArticulos.append(a.getArticuloDescripcion());
            stringArticulos.append(" ");
        }
        fila[4] = stringArticulos;
        fila[5] = new DecimalFormat("0.00").format(venta.getMonto());

        modeloTablaVenta.addRow(fila);

    }

    private void mostrarDetalleVenta() {

        if (tblVentas.getSelectedRow() != -1) {
            Venta venta = VentaFacade.getInstance().buscar((Long) tblVentas.getValueAt(tblVentas.getSelectedRow(), 0));
            modeloTablaDetalle = new ModeloTablaNoEditable();
            cargarEncabezadosTablaDetalle(modeloTablaDetalle);
            configurarTablaVentas(tblDetalle);
            try {
                cargarDetalle(venta.getVentasArticulos());
            } catch (Exception ex) {
                Logger.getLogger(DiagDetalleVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
            Comunes.setOcultarColumnasJTable(tblDetalle, 0);
        }

    }

    private void cargarDetalle(List<VentaArticulo> listaVentaArticulos) {
        try {
            modeloTablaDetalle = new ModeloTablaNoEditable();
            cargarEncabezadosTablaDetalle(modeloTablaDetalle);
            for (VentaArticulo ventaArt : listaVentaArticulos) {
                cargarArticulos(ventaArt);
            }
            tblDetalle.setModel(modeloTablaDetalle);
            Comunes.setOcultarColumnasJTable(tblDetalle, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagDetalleVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarArticulos(VentaArticulo ventaArticulo) {

        Object[] fila = new Object[7];
        fila[0] = ventaArticulo.getId();
        fila[1] = ventaArticulo.getArticuloCodigo();
        fila[2] = ventaArticulo.getArticuloDescripcion();
        fila[3] = new DecimalFormat("0.00").format(ventaArticulo.getCantidadPeso());
        fila[4] = ventaArticulo.getPrecioUnitario();
        fila[5] = new DecimalFormat("0.00").format(Double.parseDouble(ventaArticulo.getPrecioPromocion().toString()));
        fila[6] = new DecimalFormat("0.00").format(Double.parseDouble(ventaArticulo.getPrecio().toString()));
        modeloTablaDetalle.addRow(fila);
    }

    private void cargarEncabezadosTablaDetalle(ModeloTablaNoEditable modeloTablaDetalle) {
        modeloTablaDetalle.addColumn("Id");
        modeloTablaDetalle.addColumn("Codigo");
        modeloTablaDetalle.addColumn("Articulo");
        modeloTablaDetalle.addColumn("Peso Neto/Cantidad");
        modeloTablaDetalle.addColumn("Precio U.");
        modeloTablaDetalle.addColumn("Promo");
        modeloTablaDetalle.addColumn("SubTotal");
        tblDetalle.setModel(modeloTablaDetalle);
    }
}
