/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.caja.CuponTarjeta;
import entidades.caja.PlanTarjeta;
import entidades.caja.TarjetaDeCredito;
import facade.CuponTarjetaFacade;
import facade.PlanTarjetaFacade;
import facade.TarjetaDeCreditoFacade;
import includes.Comunes;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class diagCobroTarjetaCuentaC extends javax.swing.JDialog {

    /**
     * Creates new form diagCobroTarjetaVale
     */
    private BigDecimal monto = new BigDecimal("0.0");
    private CuponTarjeta cuponTarjeta;
    private BigDecimal recargo = new BigDecimal("0.0");
    private BigDecimal totalAPagarTarjeta = new BigDecimal("0.0");
    private BigDecimal totalConRecargo = new BigDecimal("0.0");

    public BigDecimal getTotalConRecargo() {
        return totalConRecargo;
    }

    public CuponTarjeta getCuponTarjeta() {
        return cuponTarjeta;
    }

    public diagCobroTarjetaCuentaC(java.awt.Frame parent, boolean modal, BigDecimal monto) {
        super(parent, modal);
        initComponents();
        this.monto = monto;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboTarjeta = new javax.swing.JComboBox();
        cboPlanTarjeta = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tfRecargo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfLote = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNroCupon = new javax.swing.JTextField();
        ftfImporteOriginalTarjeta = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tfImporteAPagar = new javax.swing.JTextField();
        tfTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.title")); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jPanel5.border.title"))); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel8.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel9.text")); // NOI18N

        cboTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTarjetaItemStateChanged(evt);
            }
        });
        cboTarjeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cboTarjetaKeyPressed(evt);
            }
        });

        cboPlanTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPlanTarjeta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPlanTarjetaItemStateChanged(evt);
            }
        });

        jLabel10.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel10.text")); // NOI18N

        tfRecargo.setEditable(false);
        tfRecargo.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.tfRecargo.text")); // NOI18N
        tfRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfRecargoActionPerformed(evt);
            }
        });

        jLabel12.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel12.text")); // NOI18N

        tfLote.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.tfLote.text")); // NOI18N
        tfLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLoteActionPerformed(evt);
            }
        });

        jLabel13.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel13.text")); // NOI18N

        tfNroCupon.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.tfNroCupon.text")); // NOI18N
        tfNroCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNroCuponActionPerformed(evt);
            }
        });

        ftfImporteOriginalTarjeta.setEditable(false);
        ftfImporteOriginalTarjeta.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.ftfImporteOriginalTarjeta.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel5.text")); // NOI18N

        tfImporteAPagar.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.tfImporteAPagar.text")); // NOI18N
        tfImporteAPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImporteAPagarActionPerformed(evt);
            }
        });
        tfImporteAPagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfImporteAPagarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfImporteAPagarKeyTyped(evt);
            }
        });

        tfTotal.setEditable(false);
        tfTotal.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.tfTotal.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboTarjeta, javax.swing.GroupLayout.Alignment.LEADING, 0, 231, Short.MAX_VALUE)
                    .addComponent(tfLote, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfImporteOriginalTarjeta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfRecargo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTotal, javax.swing.GroupLayout.Alignment.LEADING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboPlanTarjeta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfImporteAPagar))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNroCupon, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfImporteAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ftfImporteOriginalTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboPlanTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(tfNroCupon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(tfRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        btnAceptar.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(diagCobroTarjetaCuentaC.class, "diagCobroTarjetaCuentaC.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfImporteAPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImporteAPagarActionPerformed
        // TODO add your handling code here:
        try {
            calcularRecargo();
        } catch (Exception e) {
        }
        cboTarjeta.requestFocus();
    }//GEN-LAST:event_tfImporteAPagarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        cuponTarjeta = null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cboTarjetaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cboTarjetaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Comunes.cargarJCombo(cboPlanTarjeta, PlanTarjetaFacade.getInstance().getPlanUnSoloPago((TarjetaDeCredito) cboTarjeta.getSelectedItem()));
            cboPlanTarjeta.requestFocus();
        }

    }//GEN-LAST:event_cboTarjetaKeyPressed

    private void cboTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTarjetaItemStateChanged
        // TODO add your handling code here:
        Comunes.cargarJCombo(cboPlanTarjeta, PlanTarjetaFacade.getInstance().getPlanUnSoloPago((TarjetaDeCredito) cboTarjeta.getSelectedItem()));
        try {
            calcularRecargo();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_cboTarjetaItemStateChanged

    private void cboPlanTarjetaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPlanTarjetaItemStateChanged
        try {
            calcularRecargo();
        } catch (Exception e) {
        }
        tfNroCupon.requestFocus();
    }//GEN-LAST:event_cboPlanTarjetaItemStateChanged

    private void tfRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfRecargoActionPerformed
        tfNroCupon.requestFocus();
    }//GEN-LAST:event_tfRecargoActionPerformed

    private void tfNroCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNroCuponActionPerformed
        tfLote.requestFocus();
    }//GEN-LAST:event_tfNroCuponActionPerformed

    private void tfLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLoteActionPerformed
        btnAceptar.requestFocus();
    }//GEN-LAST:event_tfLoteActionPerformed

    private void tfImporteAPagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteAPagarKeyTyped
        Comunes.soloNumeros(tfImporteAPagar, evt);
    }//GEN-LAST:event_tfImporteAPagarKeyTyped

    private void tfImporteAPagarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteAPagarKeyReleased
        // TODO add your handling code here:
        try {
            calcularRecargo();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tfImporteAPagarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagCobroTarjetaCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagCobroTarjetaCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagCobroTarjetaCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagCobroTarjetaCuentaC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagCobroTarjetaCuentaC dialog = new diagCobroTarjetaCuentaC(new javax.swing.JFrame(), true, new BigDecimal("0.0"));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox cboPlanTarjeta;
    private javax.swing.JComboBox cboTarjeta;
    private javax.swing.JFormattedTextField ftfImporteOriginalTarjeta;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField tfImporteAPagar;
    private javax.swing.JTextField tfLote;
    private javax.swing.JTextField tfNroCupon;
    private javax.swing.JTextField tfRecargo;
    private javax.swing.JTextField tfTotal;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        Comunes.cargarJCombo(cboTarjeta, TarjetaDeCreditoFacade.getInstance().getTodos());
        Comunes.cargarJCombo(cboPlanTarjeta, PlanTarjetaFacade.getInstance().getPlanUnSoloPago((TarjetaDeCredito) cboTarjeta.getSelectedItem()));
        //ftfImporteOriginalTarjeta.setText(new DecimalFormat("0.00").format(monto));
        ftfImporteOriginalTarjeta.setText(monto.toString());
        //tfImporteAPagar.setText(new DecimalFormat("0.00").format(monto));
        tfImporteAPagar.setText(monto.toString());
        tfImporteAPagar.setEditable(false);
        //calculamos el recargo
        try {
            calcularRecargo();
        } catch (Exception e) {
            System.out.println("no calculo el recargo");
        }
    }

    private void aceptar() {
        if (validar()) {
            cuponTarjeta = new CuponTarjeta();
            cuponTarjeta.setImporteCupon(BigDecimal.valueOf(Double.parseDouble(tfImporteAPagar.getText().replace(",", "."))));
            cuponTarjeta.setImporteCuponConRecargo(BigDecimal.valueOf(Double.parseDouble(tfTotal.getText().replace(",", "."))));
            cuponTarjeta.setPlanTarjeta((PlanTarjeta) cboPlanTarjeta.getSelectedItem());
            cuponTarjeta.setEsCuentaCorriente(Boolean.TRUE);

            try {
                cuponTarjeta.setLote(tfLote.getText());
            } catch (Exception e) {
                cuponTarjeta.setLote("");
            }
            try {
                cuponTarjeta.setNroCupon(Integer.parseInt(tfNroCupon.getText()));
            } catch (Exception e) {

            }
            try {
                cuponTarjeta.setRecargo(BigDecimal.valueOf(Double.parseDouble(tfRecargo.getText())));
            } catch (Exception e) {

            }
            this.dispose();
        }

    }

    private boolean validar() {
        if (tfImporteAPagar.getText().isEmpty() && !Comunes.validarBigDecimal(tfImporteAPagar.getText())) {
            JOptionPane.showMessageDialog(null, "debe cargar un importe a pagar");
            tfImporteAPagar.requestFocus();
            return false;
        }

        if (monto.subtract(BigDecimal.valueOf(Double.parseDouble(tfImporteAPagar.getText().replace(",", ".")))).signum() == -1) {
            JOptionPane.showMessageDialog(null, "Importe a pagar mayor que el saldo");
            tfImporteAPagar.requestFocus();
            return false;
        }
        if (!tfNroCupon.getText().isEmpty() && !Comunes.validarInteger(tfNroCupon.getText())) {
            JOptionPane.showMessageDialog(null, "debe cargar correctamente el nro de cupon");
            tfNroCupon.requestFocus();
            return false;
        }
        if (!tfRecargo.getText().isEmpty() && !Comunes.validarBigDecimal(tfRecargo.getText())) {
            JOptionPane.showMessageDialog(null, "debe cargar correctamente el recargo");
            tfRecargo.requestFocus();
            return false;
        }
        if (cboPlanTarjeta.getSelectedItem()==null) {
            JOptionPane.showMessageDialog(null, "debe cargar plan tarjeta");
            cboPlanTarjeta.requestFocus();
            return false;
        }
        return true;
    }

    private void calcularRecargo() {
        if (Comunes.validarBigDecimal(tfImporteAPagar.getText())) {
            recargo = ((PlanTarjeta) cboPlanTarjeta.getSelectedItem()).getCoeficiente().multiply(BigDecimal.valueOf(Double.parseDouble(tfImporteAPagar.getText().replace(",", ".")))).divide(BigDecimal.valueOf(100));
            //tfRecargo.setText(new DecimalFormat("0.00").format(recargo));
            tfRecargo.setText(recargo.toString());
            totalAPagarTarjeta = recargo.add(BigDecimal.valueOf(Double.parseDouble(tfImporteAPagar.getText().replace(",", "."))));
            //tfTotal.setText(new DecimalFormat("0.00").format(totalAPagarTarjeta));
            tfTotal.setText(totalAPagarTarjeta.toString());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Formato numerico no valido");
        }

    }
}
