/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.Sucursal;
import entidades.caja.Caja;
import entidades.caja.RetiroEfectivo;
import entidades.caja.TipoDeFactura;
import entidades.usuario.Usuario;
import facade.CajaFacade;
import facade.MovimientoCajaFacade;
import facade.GenericoFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bangho
 */
public class DiagRetiroEfectivo extends javax.swing.JDialog {

    private ModeloTablaNoEditable modeloTablaRetiroEfectivos;
    private RetiroEfectivo retiroEfectivo;
    private Usuario usuario;
    private Sucursal sucursal;
    private Caja caja;

    /**
     * Creates new form DiagRetiroEfectivos
     *
     * @param parent
     * @param modal
     * @param usuario
     * @param sucursal
     */
    public DiagRetiroEfectivo(java.awt.Frame parent, boolean modal, Usuario usuario, Sucursal sucursal, Caja caja) {
        super(parent, modal);
        initComponents();
        this.usuario = usuario;
        this.sucursal = sucursal;
        this.caja = caja;
        this.setTitle("Egresos");
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRetiroEfectivos = new javax.swing.JTable();
        tfImporte = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ftfHora = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.jPanel1.border.title"))); // NOI18N

        tblRetiroEfectivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblRetiroEfectivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRetiroEfectivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRetiroEfectivos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        tfImporte.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.tfImporte.text")); // NOI18N
        tfImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfImporteKeyTyped(evt);
            }
        });

        tfDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.tfDescripcion.text")); // NOI18N

        dpFecha.setFormats("dd/MM/yyyy");

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.jLabel3.text")); // NOI18N

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.btnAgregar.text")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnModificar.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.btnModificar.text")); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminar.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.btnEliminar.text")); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.jLabel5.text")); // NOI18N

        try {
            ftfHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText(org.openide.util.NbBundle.getMessage(DiagRetiroEfectivo.class, "DiagRetiroEfectivo.jLabel9.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ftfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfImporte)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ftfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        altaRetiroEfectivo();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblRetiroEfectivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRetiroEfectivosMouseClicked
        cargarParaModificarRetiroEfectivo();
    }//GEN-LAST:event_tblRetiroEfectivosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarRetiroEfectivo();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarRetiroEfectivo();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tfImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteKeyTyped
        // TODO add your handling code here:
        Comunes.soloNumeros(tfImporte, evt);
    }//GEN-LAST:event_tfImporteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagRetiroEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagRetiroEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagRetiroEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagRetiroEfectivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagRetiroEfectivo dialog = new DiagRetiroEfectivo(new javax.swing.JFrame(), true, new Usuario(), new Sucursal(), new Caja());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private boolean validarRetiroEfectivo() {
        if (tfImporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe tipear un importe");
            tfImporte.grabFocus();
            return false;
        }
        if (tfDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe tipear la descripcion");
            tfDescripcion.grabFocus();
            return false;
        }
        if (ftfHora.getText().equals("  :  ")) {
            JOptionPane.showMessageDialog(null, "Debe cargar la hora en formato HH:MM   ejemplo 16:30");
            ftfHora.grabFocus();
            return false;
        }
        if (Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()) == null) {
            JOptionPane.showMessageDialog(null, "Debe cargar correctamente el formato ejemplo 16:30");
            ftfHora.grabFocus();
            return false;
        }
        return true;
    }

    private void cargarTablaRetiroEfectivos(List<RetiroEfectivo> retiroEfectivos) {
        modeloTablaRetiroEfectivos = new ModeloTablaNoEditable();
        cargarEncabezadosTablaRetiroEfectivos(modeloTablaRetiroEfectivos);
        configurarTabla(tblRetiroEfectivos);
        try {
            cargarRetiroEfectivos(retiroEfectivos);
        } catch (Exception ex) {
            Logger.getLogger(DiagSueldosAdelantos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarEncabezadosTablaRetiroEfectivos(ModeloTablaNoEditable modeloTablaRetiroEfectivos) {
        modeloTablaRetiroEfectivos.addColumn("Id");
        modeloTablaRetiroEfectivos.addColumn("Fecha");
        modeloTablaRetiroEfectivos.addColumn("Importe");
        modeloTablaRetiroEfectivos.addColumn("Observaciones");
        tblRetiroEfectivos.setModel(modeloTablaRetiroEfectivos);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarRetiroEfectivos(List<RetiroEfectivo> retiroEfectivos) {
        try {
            modeloTablaRetiroEfectivos = new ModeloTablaNoEditable();
            cargarEncabezadosTablaRetiroEfectivos(modeloTablaRetiroEfectivos);
            for (RetiroEfectivo g : retiroEfectivos) {
                cargarRetiroEfectivo(g);
            }

            tblRetiroEfectivos.setModel(modeloTablaRetiroEfectivos);
            Comunes.setOcultarColumnasJTable(tblRetiroEfectivos, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagSueldosAdelantos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarRetiroEfectivo(RetiroEfectivo retiroEfectivo) {
        Object[] fila = new Object[4];
        fila[0] = retiroEfectivo.getId();
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        try {
            fila[1] = formats.format(retiroEfectivo.getFecha());
        } catch (Exception e) {

        }
        fila[2] = retiroEfectivo.getImporte();
        fila[3] = retiroEfectivo.getDescripcion();
        modeloTablaRetiroEfectivos.addRow(fila);
    }

    private void cargarRetiroEfectivo() {
        retiroEfectivo = (RetiroEfectivo) MovimientoCajaFacade.getInstance().buscar((Long) tblRetiroEfectivos.getValueAt(tblRetiroEfectivos.getSelectedRow(), 0));
        tfImporte.setText(String.valueOf(retiroEfectivo.getImporte()));
        tfDescripcion.setText(retiroEfectivo.getDescripcion());
        dpFecha.setDate(retiroEfectivo.getFecha());
        try {
            ftfHora.setText(Comunes.extraerHoraDeFecha(retiroEfectivo.getFecha()));
        } catch (Exception e) {
        }

    }

    private void eliminarRetiroEfectivo() {
        try {
            MovimientoCajaFacade.getInstance().eliminar(retiroEfectivo.getId());
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            cargarTablaRetiroEfectivos(MovimientoCajaFacade.getInstance().getRetiroEfectivos(caja.getFechaInicio()));
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    private void limpiar() {
        retiroEfectivo = new RetiroEfectivo();
        tfDescripcion.setText("");
        tfImporte.setText("");
        ftfHora.setText("");
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JFormattedTextField ftfHora;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRetiroEfectivos;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfImporte;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        //CARGAR TABLA CON ADELANTOS DE SUELDO
        caja = CajaFacade.getInstance().getCajaAbierta(sucursal, usuario);
        if (caja == null) {
            Comunes.mensajeError("Es posible que no se haya abierto caja", "No existe caja abierta");
            this.dispose();
        }    //CARGAR TABLA CON ADELANTOS DE SUELDO
        cargarTablaRetiroEfectivos(MovimientoCajaFacade.getInstance().getRetiroEfectivos(caja.getFechaInicio()));
        Comunes.setOcultarColumnasJTable(tblRetiroEfectivos, 0);
        //CARGAR COMBO LISTA EMPLEADOS
        //Carga tipo de factura
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    private void altaRetiroEfectivo() {

        if (validarRetiroEfectivo()) {

//            try {
            caja = CajaFacade.getInstance().getCajaAbierta(sucursal, usuario);

            BigDecimal saldoFinalCaja = CajaFacade.getInstance().getSaldoFinalCaja(caja);

            //obtenemos el importe del retiroEfectivo
            BigDecimal importeRetiroEfectivo = new BigDecimal(tfImporte.getText());
            if (saldoFinalCaja.compareTo(importeRetiroEfectivo) >= 0) {
                retiroEfectivo = new RetiroEfectivo();
//                retiroEfectivo.setFecha(dpFecha.getDate());
                retiroEfectivo.setFecha(Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()));
                retiroEfectivo.setImporte(importeRetiroEfectivo);
                retiroEfectivo.setDescripcion(tfDescripcion.getText());
                retiroEfectivo.setUsuario(usuario);
                retiroEfectivo.setSucursal(sucursal);
                MovimientoCajaFacade.getInstance().alta(retiroEfectivo);
                JOptionPane.showMessageDialog(null, "Datos Registrados");
                cargarTablaRetiroEfectivos(MovimientoCajaFacade.getInstance().getRetiroEfectivos(caja.getFechaInicio()));
                limpiar();
            } else {
                JOptionPane.showMessageDialog(null, "No tiene saldo suficiente para realizar este retiro en efectivo\n"
                        + "La Caja dispone de $ " + saldoFinalCaja);
            }
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(null, "Error: " + e);
//            }
        }
    }

    private void cargarParaModificarRetiroEfectivo() {
        cargarRetiroEfectivo();
        btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }

    private void modificarRetiroEfectivo() {
        if (validarRetiroEfectivo()) {
            try {
                retiroEfectivo.setFecha(Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()));
                retiroEfectivo.setImporte(new BigDecimal(tfImporte.getText()));
                retiroEfectivo.setDescripcion(tfDescripcion.getText());
                retiroEfectivo.setUsuario(usuario);
                MovimientoCajaFacade.getInstance().modificar(retiroEfectivo);
                JOptionPane.showMessageDialog(null, "Datos modificados!!!");
                cargarTablaRetiroEfectivos(MovimientoCajaFacade.getInstance().getRetiroEfectivos(caja.getFechaInicio()));
                limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }
        }

    }

    private void filtrarRetiroEfectivos() {

        cargarRetiroEfectivos(MovimientoCajaFacade.getInstance().getRetiroEfectivos(caja.getFechaInicio()));

    }

}
