/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import vista.ventas.*;
import entidades.Sucursal;
import entidades.articulo.Articulo;
import entidades.caja.Caja;
import entidades.cliente.Organismo;
import entidades.cliente.Persona;
import entidades.persona.DocumentoIdentidad;
import entidades.persona.TipoDocumento;
import entidades.usuario.Usuario;
import entidades.venta.CierreVentas;
import entidades.venta.Venta;
import entidades.venta.VentaArticulo;
import facade.ArticuloFacade;
import facade.CajaFacade;
import facade.CierreVentasFacade;
import facade.ClienteFacade;
import facade.SucursalFacade;
import facade.TipoDocumentoFacade;
import facade.UsuarioFacade;
import facade.VentaFacade;
import includes.ExportarExcel;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author hugo
 */
public class DiagExportarImportarCaja extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private String tipoOperacion;
    private javax.swing.JTextField jTextField;
    private ModeloTablaNoEditable modeloTablaCaja;
    private Vector headers = new Vector();
    private Vector data = new Vector();
    private Venta venta;
    private VentaArticulo ventaArticulo;
    private List<VentaArticulo> listaVentaArticulos;
    private Articulo articulo;

    private Persona persona;
    private Organismo organismo;

    private DocumentoIdentidad documento;
    private TipoDocumento tipodoc;

    private Sucursal sucursal;
    private Usuario usuario;

    private int AuxTicket, AuxSucursal;
    private CierreVentas cierreVentas;
    private Caja caja;

    public DiagExportarImportarCaja(java.awt.Frame parent, boolean modal, Sucursal sucursal) {
        super(parent, modal);
        initComponents();
        this.sucursal = sucursal;
        inicializarComponentes();
    }

    public DiagExportarImportarCaja(java.awt.Frame parent, boolean modal, String tipoOperacion, Sucursal sucursal) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        this.sucursal = sucursal;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodDesc = new javax.swing.ButtonGroup();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCaja = new javax.swing.JTable();
        btnExportarArt = new javax.swing.JButton();
        btnImportarArt = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarCaja.class, "DiagExportarImportarCaja.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagExportarImportarCaja.class, "DiagExportarImportarCaja.jPanel3.border.title"))); // NOI18N

        tblCaja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Anulado", "Descuento", "Fecha", "Monto", "Numero Ticket", "Apellido Cli", "Nombre Cli", "Nro Dni", "Tipo Dni", "Razon Social", "CUIL", "Cod Sucursal", "Usu", "CantidadPeso", "PrecioxCatidad", "Precio Cobrado", "Precio Unitario", "Articulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCaja);

        btnExportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnExportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarCaja.class, "DiagExportarImportarCaja.btnExportarArt.text")); // NOI18N
        btnExportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarArtActionPerformed(evt);
            }
        });

        btnImportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnImportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarCaja.class, "DiagExportarImportarCaja.btnImportarArt.text")); // NOI18N
        btnImportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarArtActionPerformed(evt);
            }
        });

        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardarCambios.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarCaja.class, "DiagExportarImportarCaja.btnGuardarCambios.text")); // NOI18N
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambios)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnExportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarArtActionPerformed
        Exportar();
    }//GEN-LAST:event_btnExportarArtActionPerformed

    private void btnImportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarArtActionPerformed
        Importar();
    }//GEN-LAST:event_btnImportarArtActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        guardarCajas();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagExportarImportarCaja dialog = new DiagExportarImportarCaja(new javax.swing.JFrame(), true, new Sucursal());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodDesc;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportarArt;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnImportarArt;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCaja;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Exportar/Importar Caja");
        modeloTablaCaja = new ModeloTablaNoEditable();
        cargarEncabezadosTablaCaja(modeloTablaCaja);
        if (sucursal.getCodigo().equals("1")) {
            //SI ES LA CENTRAL QUE MUESTRE TODAS LAS CAJAS DE TODAS LAS SUCURSALES
            System.out.println("entro central: " + sucursal.getCodigo());
            try {
                cargarTablaCaja(CajaFacade.getInstance().getCajasCerradas());
            } catch (Exception e) {
            }
        } else {
            //MOSTRAMOS SOLO LAS CAJAS DE LA SUCURSAL
            try {
                cargarTablaCaja(CajaFacade.getInstance().getCajasCerradas(sucursal));
            } catch (Exception e) {
            }
        }

        AuxTicket = 0;
        AuxSucursal = 0;
        if (!sucursal.getNombre().toUpperCase().contains("CENTRAL")) {
            btnGuardarCambios.setEnabled(false);
            btnImportarArt.setEnabled(false);
        }
    }

    private void cargarTablaCaja(List<Caja> cajas) {
        modeloTablaCaja = new ModeloTablaNoEditable();
        cargarEncabezadosTablaCaja(modeloTablaCaja);
        configurarTabla(tblCaja);
        try {
            cargarCajas(cajas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaCaja(ModeloTablaNoEditable modeloTablaCaja) {
        modeloTablaCaja.addColumn("Id");
        modeloTablaCaja.addColumn("Caja Inicial");
        modeloTablaCaja.addColumn("Caja Final");
        modeloTablaCaja.addColumn("Fecha Apertura");
        modeloTablaCaja.addColumn("Fecha Cierre");
        modeloTablaCaja.addColumn("Sucursal");
        modeloTablaCaja.addColumn("Usuario");
        tblCaja.setModel(modeloTablaCaja);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarCajas(List<Caja> cajas) {
        try {
            modeloTablaCaja = new ModeloTablaNoEditable();
            cargarEncabezadosTablaCaja(modeloTablaCaja);
            for (Caja caja : cajas) {
                cargarCaja(caja);
            }

            tblCaja.setModel(modeloTablaCaja);
            // Comunes.setOcultarColumnasJTable(tblVentas, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagExportarImportarCaja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarCaja(Caja caja) {
        // JOptionPane.showMessageDialog(null, "va "+va.getCantidadPeso());
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        DecimalFormatSymbols simboloSeparador = new DecimalFormatSymbols(Locale.ENGLISH);
        simboloSeparador.setDecimalSeparator(',');
        DecimalFormat formatoConComa = new DecimalFormat("#####.###", simboloSeparador);
        Object[] fila = new Object[7];
        fila[0] = caja.getId();
        fila[1] = formatoConComa.format(caja.getCajaInicial());
        fila[2] = formatoConComa.format(caja.getCajaFinal());
        try {
//            fila[3]=caja.getFechaInicio();
            fila[3] = formats.format(caja.getFechaInicio());
        } catch (Exception e) {
        }
        try {
//            fila[4]=caja.getFechaFin();
            fila[4] = formats.format(caja.getFechaFin());
        } catch (Exception e) {
        }
        fila[5] = caja.getSucursal().getCodigo();
        try {
            fila[6] = caja.getUsuario().getNombreUsuario();
        } catch (Exception e) {
        }

        modeloTablaCaja.addRow(fila);
    }

    private void Exportar() {
        new ExportarExcel().crearExcelJtable(tblCaja, "Listado de Cajas");
        modeloTablaCaja = new ModeloTablaNoEditable();
        cargarEncabezadosTablaCaja(modeloTablaCaja);
    }

    private void Importar() {
        JFileChooser jChooser = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xls");
        jChooser.setFileFilter(filter);
        jChooser.showOpenDialog(this);
        File file = jChooser.getSelectedFile();
        if (file == null || !file.getName().endsWith("xls")) {
            JOptionPane.showMessageDialog(null, "Solo se permiten Archivos .xls.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            leerDatosExcel(file);
            List<Integer> columnasNoEditables = new ArrayList<>();
            columnasNoEditables.add(0);
            columnasNoEditables.add(1);
            columnasNoEditables.add(2);
            columnasNoEditables.add(3);
            columnasNoEditables.add(4);
            columnasNoEditables.add(5);
            columnasNoEditables.add(6);
            ModeloTablaNoEditable model = new ModeloTablaNoEditable(data, headers, columnasNoEditables);
            tblCaja.setModel(model);
        }
    }

    void leerDatosExcel(File file) {
        Workbook workbook = null;
        try {
            try {
                workbook = Workbook.getWorkbook(file);
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
            Sheet sheet = workbook.getSheet(0);
            headers.clear();
            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                headers.add(cell1.getContents());
            }
            data.clear();
            for (int j = 1; j < sheet.getRows(); j++) {
                Vector d = new Vector();
                for (int i = 0; i < sheet.getColumns(); i++) {
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

    private void guardarCajas() {
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss");
        try {
            for (int i = 0; i < tblCaja.getRowCount(); i++) {

                //si no existe la caja la creamos
                if (!CajaFacade.getInstance().existeCajaSucursal(formats.parse(tblCaja.getValueAt(i, 3).toString()), (String) tblCaja.getValueAt(i, 5), (String) tblCaja.getValueAt(i, 6))) {

                    caja = new Caja();
                    caja.setCajaFinal(new BigDecimal((String) tblCaja.getValueAt(i, 2)));
                    caja.setCajaInicial(new BigDecimal((String) tblCaja.getValueAt(i, 1)));
                    caja.setFechaInicio(formats.parse(tblCaja.getValueAt(i, 3).toString()));
                    caja.setFechaFin(formats.parse(tblCaja.getValueAt(i, 4).toString()));
                    caja.setSucursal(sucursal);
                    caja.setUsuario(usuario);
                    CajaFacade.getInstance().alta(caja);

                } else {
                    JOptionPane.showMessageDialog(null, "caja ya existe");
                }

            }
            JOptionPane.showMessageDialog(null, "Importacion de Cajas Realizada");
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }
    }

}
