/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import Recursos.SoapNoEnviados;
import entidades.caja.Caja;
import entidades.caja.CuentaCorriente;
import entidades.caja.CuponTarjeta;
import facade.CajaFacade;
import facade.CuponTarjetaFacade;
import includes.Comunes;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author root
 */
public class DiagResumenCierreCaja extends javax.swing.JDialog {

    private Caja caja;
    private boolean cerrarCaja;
    private BigDecimal totalCreditoCtaCte = new BigDecimal("0.000");
    private BigDecimal totalCuponesTarjeta = new BigDecimal("0.000");
    private BigDecimal totalVale = new BigDecimal("0.000");
    private BigDecimal diferencia = new BigDecimal("0.000");

    /**
     * Creates new form DiagResumenCierreCaja
     *
     * @return
     */
    public boolean isCerrarCaja() {
        return cerrarCaja;
    }

    public Caja getCaja() {
        return caja;
    }

    public DiagResumenCierreCaja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DiagResumenCierreCaja(java.awt.Frame parent, boolean modal, Caja caja) {
        super(parent, modal);
        initComponents();
        this.caja = caja;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfSucursal = new javax.swing.JTextField();
        tfUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfFechaInicio = new javax.swing.JTextField();
        tfFechaCierre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfCajaInicial = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tfVentas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfCobranzasCtaCte = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfIngresoVarios = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfGastos = new javax.swing.JTextField();
        tfSueldosYAdelantos = new javax.swing.JTextField();
        tfTotalEgresos = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfRetirosEfectivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfTotalCuentaCorriente = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfTotalTarjetaCredito = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        tfTotalVale = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tfSaldoDeCaja = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        tfSaldoDeCajaReal = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfDiferenciaCaja = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jPanel1.border.title"))); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel3.text")); // NOI18N

        tfSucursal.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfSucursal.text")); // NOI18N

        tfUsuario.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfUsuario.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel4.text")); // NOI18N

        tfFechaInicio.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfFechaInicio.text")); // NOI18N

        tfFechaCierre.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfFechaCierre.text")); // NOI18N

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel5.text")); // NOI18N

        jLabel6.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel6.text")); // NOI18N

        tfCajaInicial.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfCajaInicial.text")); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jPanel2.border.title"))); // NOI18N

        jLabel12.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel12.text")); // NOI18N

        tfVentas.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfVentas.text")); // NOI18N

        jLabel13.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel13.text")); // NOI18N

        tfCobranzasCtaCte.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfCobranzasCtaCte.text")); // NOI18N

        jLabel14.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel14.text")); // NOI18N

        tfIngresoVarios.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfIngresoVarios.text")); // NOI18N

        jLabel15.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel15.text")); // NOI18N

        tfTotal.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfTotal.text")); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfIngresoVarios, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCobranzasCtaCte, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfVentas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tfCobranzasCtaCte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfIngresoVarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jPanel3.border.title"))); // NOI18N

        jLabel18.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel18.text")); // NOI18N

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel17.text")); // NOI18N

        jLabel16.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel16.text")); // NOI18N

        tfGastos.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfGastos.text")); // NOI18N

        tfSueldosYAdelantos.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfSueldosYAdelantos.text")); // NOI18N

        tfTotalEgresos.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfTotalEgresos.text")); // NOI18N

        jLabel19.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel19.text")); // NOI18N

        tfRetirosEfectivo.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfRetirosEfectivo.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSueldosYAdelantos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTotalEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfRetirosEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tfSueldosYAdelantos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfGastos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(tfRetirosEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addContainerGap())
        );

        jLabel7.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel7.text")); // NOI18N

        jLabel8.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel8.text")); // NOI18N

        tfTotalCuentaCorriente.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfTotalCuentaCorriente.text")); // NOI18N

        jLabel9.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel9.text")); // NOI18N

        jLabel10.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel10.text")); // NOI18N

        tfTotalTarjetaCredito.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfTotalTarjetaCredito.text")); // NOI18N

        jLabel20.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel20.text")); // NOI18N

        jLabel21.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel21.text")); // NOI18N

        tfTotalVale.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfTotalVale.text")); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jPanel4.border.title"))); // NOI18N

        jLabel11.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel11.text")); // NOI18N

        tfSaldoDeCaja.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfSaldoDeCaja.text")); // NOI18N

        jLabel22.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel22.text")); // NOI18N

        tfSaldoDeCajaReal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        tfSaldoDeCajaReal.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfSaldoDeCajaReal.text")); // NOI18N
        tfSaldoDeCajaReal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSaldoDeCajaRealKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSaldoDeCajaRealKeyTyped(evt);
            }
        });

        jLabel23.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.jLabel23.text")); // NOI18N

        tfDiferenciaCaja.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.tfDiferenciaCaja.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(tfSaldoDeCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(tfSaldoDeCajaReal, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(52, 52, 52)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfDiferenciaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel23)))
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDiferenciaCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfSaldoDeCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSaldoDeCajaReal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addGap(92, 92, 92))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfTotalTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(tfUsuario))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel5))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFechaInicio)
                            .addComponent(tfFechaCierre)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(tfCajaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTotalVale, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel20)))
                        .addGap(14, 14, 14)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFechaCierre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCajaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tfTotalCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfTotalTarjetaCredito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfTotalVale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        btnAceptar.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCancelar.setText(org.openide.util.NbBundle.getMessage(DiagResumenCierreCaja.class, "DiagResumenCierreCaja.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ReintentarEnviarVentasFidelizadasConError();
        this.cerrarCaja = true;
        this.caja.setCajaFinal(new BigDecimal(tfSaldoDeCajaReal.getText()));
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.cerrarCaja = false;
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfSaldoDeCajaRealKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSaldoDeCajaRealKeyReleased
        Comunes.soloNumeros(tfSaldoDeCajaReal, evt);
        calcular();
    }//GEN-LAST:event_tfSaldoDeCajaRealKeyReleased

    private void tfSaldoDeCajaRealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSaldoDeCajaRealKeyTyped
        // TODO add your handling code here:
        Comunes.soloNumeros(tfSaldoDeCajaReal, evt);
    }//GEN-LAST:event_tfSaldoDeCajaRealKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagResumenCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagResumenCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagResumenCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagResumenCierreCaja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagResumenCierreCaja dialog = new DiagResumenCierreCaja(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tfCajaInicial;
    private javax.swing.JTextField tfCobranzasCtaCte;
    private javax.swing.JTextField tfDiferenciaCaja;
    private javax.swing.JTextField tfFechaCierre;
    private javax.swing.JTextField tfFechaInicio;
    private javax.swing.JTextField tfGastos;
    private javax.swing.JTextField tfIngresoVarios;
    private javax.swing.JTextField tfRetirosEfectivo;
    private javax.swing.JTextField tfSaldoDeCaja;
    private javax.swing.JTextField tfSaldoDeCajaReal;
    private javax.swing.JTextField tfSucursal;
    private javax.swing.JTextField tfSueldosYAdelantos;
    private javax.swing.JTextField tfTotal;
    private javax.swing.JTextField tfTotalCuentaCorriente;
    private javax.swing.JTextField tfTotalEgresos;
    private javax.swing.JTextField tfTotalTarjetaCredito;
    private javax.swing.JTextField tfTotalVale;
    private javax.swing.JTextField tfUsuario;
    private javax.swing.JTextField tfVentas;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        deshabilitarComponetes();
        try {
            tfSucursal.setText(caja.getSucursal().toString());
        } catch (Exception e) {
        }
        try {
            tfUsuario.setText(caja.getUsuario().toString());
        } catch (Exception e) {
        }
        try {
            tfFechaInicio.setText(formateador.format(caja.getFechaInicio()));
        } catch (Exception e) {
        }
        try {
            tfFechaCierre.setText(formateador.format(caja.getFechaFin()));
        } catch (Exception e) {
        }
        try {
            tfCajaInicial.setText(new DecimalFormat("0.000").format(caja.getCajaInicial()));
        } catch (Exception e) {
        }
        try {
            tfVentas.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getCobroVentas(caja)));
        } catch (Exception e) {
        }
        try {
            //AQUI RESTAMOS DE LAAS COBRANZAS DE CTA CTE.. LAS COBRANZA EN CTA CTE COBRADAS CON TARJETA
            // YA QUE ESTAS ULTIMAS NO REPRESENTAN INGRESO DE CAJA
            BigDecimal cuponesCtaCteConTarjeta = new BigDecimal("0.000");
            BigDecimal cobranzaCtaCteConTarjeta;
            for (CuponTarjeta cupon : CuponTarjetaFacade.getInstance().getCuponesTarjetaCtaCteCaja(caja.getFechaInicio())) {
                cuponesCtaCteConTarjeta = cuponesCtaCteConTarjeta.add(cupon.getImporteCuponConRecargo());
            }
            cobranzaCtaCteConTarjeta = CajaFacade.getInstance().getCobranazaCtaCteCaja(caja);
            cobranzaCtaCteConTarjeta = cobranzaCtaCteConTarjeta.subtract(cuponesCtaCteConTarjeta);

            tfCobranzasCtaCte.setText(new DecimalFormat("0.000").format(cobranzaCtaCteConTarjeta));
        } catch (Exception e) {
        }
        try {
            tfIngresoVarios.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getIngresosVarios(caja)));
        } catch (Exception e) {
        }
        try {
            tfTotal.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getTotalIngresos(caja)));
        } catch (Exception e) {
        }
        try {
            tfSueldosYAdelantos.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getSueldosyAdelantos(caja)));
        } catch (Exception e) {
        }
        try {
            tfGastos.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getGastos(caja)));
        } catch (Exception e) {
        }
        try {
            tfRetirosEfectivo.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getRetirosEfectivo(caja)));
        } catch (Exception e) {
        }
        try {
            tfTotalEgresos.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getTotalEgresos(caja)));
        } catch (Exception e) {
        }
        try {
            //cuenta corriente
            for (CuentaCorriente cc : caja.getMovimientosCtaCte()) {
                totalCreditoCtaCte = totalCreditoCtaCte.add(cc.getImporteCtaCte());
            }
            tfTotalCuentaCorriente.setText(new DecimalFormat("0.000").format(totalCreditoCtaCte));
        } catch (Exception e) {
        }

        try {
            // TARJETA DE CREDITO y VALES(nuevo)
            for (CuponTarjeta cuponTarjeta : caja.getMovimientosCuponesTarjeta()) {
                if (!cuponTarjeta.getPlanTarjeta().getEsVale()) {
                    totalCuponesTarjeta = totalCuponesTarjeta.add(cuponTarjeta.getImporteCuponConRecargo());
                } else {
                    totalVale = totalVale.add(cuponTarjeta.getImporteCuponConRecargo());
                }

            }
            tfTotalTarjetaCredito.setText(new DecimalFormat("0.000").format(totalCuponesTarjeta));
            tfTotalVale.setText(new DecimalFormat("0.000").format(totalVale));
        } catch (Exception e) {
        }
        try {
            // saldo de caja
            tfSaldoDeCaja.setText(new DecimalFormat("0.000").format(CajaFacade.getInstance().getSaldoFinalCaja(caja)));
        } catch (Exception e) {
        }

    }

    private void deshabilitarComponetes() {
        tfSucursal.setEditable(false);
        tfUsuario.setEditable(false);
        tfFechaInicio.setEditable(false);
        tfFechaCierre.setEditable(false);
        tfCajaInicial.setEditable(false);
        tfVentas.setEditable(false);
        tfCobranzasCtaCte.setEditable(false);
        tfIngresoVarios.setEditable(false);
        tfTotal.setEditable(false);
        tfSueldosYAdelantos.setEditable(false);
        tfGastos.setEditable(false);
        tfRetirosEfectivo.setEditable(false);
        tfTotalEgresos.setEditable(false);
        tfTotalCuentaCorriente.setEditable(false);
        tfTotalTarjetaCredito.setEditable(false);
        tfSaldoDeCaja.setEditable(false);
        tfTotalVale.setEditable(false);
        btnAceptar.setEnabled(false);

    }

    private void calcular() {
        if (!tfSaldoDeCajaReal.getText().isEmpty()) {
            calcularDiferenciaCaja();
        } else {
            tfDiferenciaCaja.setText("");
        }
    }

    private void calcularDiferenciaCaja() {
        if (!tfSaldoDeCajaReal.getText().isEmpty() && Comunes.validarBigDecimal(tfSaldoDeCajaReal.getText())) {
            if (new BigDecimal(tfSaldoDeCajaReal.getText().replace(",", ".")).signum() >= 0
                    && new BigDecimal(tfSaldoDeCaja.getText().replace(",", ".")).signum() >= 0) {
                //calculamos diferencia
                diferencia = new BigDecimal(tfSaldoDeCajaReal.getText().replace(",", "."))
                        .subtract(new BigDecimal(tfSaldoDeCaja.getText().replace(",", ".")));
                if (diferencia.signum() > -1) {
                    btnAceptar.setEnabled(true);
                    tfDiferenciaCaja.setForeground(Color.black);
                    tfDiferenciaCaja.setText(diferencia.toString());
                } else {
                    btnAceptar.setEnabled(false);
                    tfDiferenciaCaja.setForeground(Color.red);
                    tfDiferenciaCaja.setText(diferencia.toString());
                }

            }
        } else {
            tfDiferenciaCaja.setText("");
        }
    }

    private void ReintentarEnviarVentasFidelizadasConError() {
        //To change body of generated methods, choose Tools | Templates.
        Runnable run = new SoapNoEnviados();
        Thread thread = new Thread(run);
        thread.start();
    }
}
