/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.Sucursal;
import entidades.caja.Caja;
import entidades.caja.Gasto;
import entidades.caja.Ingreso;
import entidades.caja.TipoDeGasto;
import entidades.caja.TipoDeIngreso;
import entidades.usuario.Usuario;
import facade.CajaFacade;
import facade.MovimientoCajaFacade;
import facade.GenericoFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author bangho
 */
public class DiagIngreso extends javax.swing.JDialog {

    private ModeloTablaNoEditable modeloTablaIngreso;
    private Ingreso ingreso;
    private Usuario usuario;
    private Sucursal sucursal;
    private Caja caja;

    /**
     * Creates new form DiagGastos
     *
     * @param parent
     * @param modal
     * @param usuario
     * @param sucursal
     * @param caja
     */
    public DiagIngreso(java.awt.Frame parent, boolean modal, Usuario usuario, Sucursal sucursal, Caja caja) {
        super(parent, modal);
        initComponents();
        this.sucursal = sucursal;
        this.usuario = usuario;
        this.caja = caja;
        this.setTitle("Ingresos");
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIngreso = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cboFiltroTipoIngreso = new javax.swing.JComboBox();
        cbTipoIngreso = new javax.swing.JComboBox();
        tfImporte = new javax.swing.JTextField();
        tfDescripcion = new javax.swing.JTextField();
        dpFecha = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        ftfHora = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jPanel1.border.title"))); // NOI18N

        tblIngreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblIngresoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblIngreso);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel4.text")); // NOI18N

        cboFiltroTipoIngreso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboFiltroTipoIngreso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboFiltroTipoIngresoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboFiltroTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboFiltroTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tfImporte.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.tfImporte.text")); // NOI18N
        tfImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfImporteKeyTyped(evt);
            }
        });

        tfDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.tfDescripcion.text")); // NOI18N

        dpFecha.setFormats("dd/MM/yyyy");

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel3.text")); // NOI18N

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.btnAgregar.text")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnModificar.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.btnModificar.text")); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminar.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.btnEliminar.text")); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel5.text")); // NOI18N

        try {
            ftfHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText(org.openide.util.NbBundle.getMessage(DiagIngreso.class, "DiagIngreso.jLabel9.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(ftfHora, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfDescripcion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbTipoIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel9))
                                        .addGap(2, 2, 2)
                                        .addComponent(tfImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(2, 2, 2)
                                        .addComponent(dpFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ftfHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        altaIngreso();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tblIngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblIngresoMouseClicked
        cargarParaModificarIngreso();
    }//GEN-LAST:event_tblIngresoMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificarIngreso();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        eliminarIngreso();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboFiltroTipoIngresoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboFiltroTipoIngresoItemStateChanged
        filtrarIngresos();
    }//GEN-LAST:event_cboFiltroTipoIngresoItemStateChanged

    private void tfImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteKeyTyped
        // TODO add your handling code here:
        Comunes.soloNumeros(tfImporte, evt);
    }//GEN-LAST:event_tfImporteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagIngreso dialog = new DiagIngreso(new javax.swing.JFrame(), true, new Usuario(), new Sucursal(), new Caja());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void cargarTipoDeIngreso() {
        Comunes.cargarJComboConBlanco(cboFiltroTipoIngreso, GenericoFacade.getInstance().find("TipoDeIngreso"));
        Comunes.cargarJCombo(cbTipoIngreso, GenericoFacade.getInstance().find("TipoDeIngreso"));
    }

    private boolean validarIngreso() {
        if (tfImporte.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe tipear un importe");
            tfImporte.grabFocus();
            return false;
        }
        if (tfDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe tipear la descripcion");
            tfDescripcion.grabFocus();
            return false;
        }
        if (ftfHora.getText().equals("  :  ")) {
            JOptionPane.showMessageDialog(null, "Debe cargar la hora en formato HH:MM   ejemplo 16:30");
            ftfHora.grabFocus();
            return false;
        }
        if (Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()) == null) {
            JOptionPane.showMessageDialog(null, "Debe cargar correctamente el formato ejemplo 16:30");
            ftfHora.grabFocus();
            return false;
        }
        return true;

    }

    private void cargarTablaIngreso(List<Ingreso> ingresos) {
        modeloTablaIngreso = new ModeloTablaNoEditable();
        cargarEncabezadosTablaIngreso(modeloTablaIngreso);
        configurarTabla(tblIngreso);
        try {
            cargarIngresos(ingresos);
        } catch (Exception ex) {
            Logger.getLogger(DiagIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarEncabezadosTablaIngreso(ModeloTablaNoEditable modeloTablaIngreso) {
        modeloTablaIngreso.addColumn("Id");
        modeloTablaIngreso.addColumn("Fecha");
        modeloTablaIngreso.addColumn("Tipo de Ingreso");
        modeloTablaIngreso.addColumn("Importe");
        modeloTablaIngreso.addColumn("Observaciones");
        tblIngreso.setModel(modeloTablaIngreso);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarIngresos(List<Ingreso> ingresos) {
        try {
            modeloTablaIngreso = new ModeloTablaNoEditable();
            cargarEncabezadosTablaIngreso(modeloTablaIngreso);
            for (Ingreso g : ingresos) {
                cargarIngreso(g);
            }

            tblIngreso.setModel(modeloTablaIngreso);
            Comunes.setOcultarColumnasJTable(tblIngreso, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagIngreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarIngreso(Ingreso ingreso) {
        Object[] fila = new Object[5];
        fila[0] = ingreso.getId();
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        try {
            fila[1] = formats.format(ingreso.getFecha());
        } catch (Exception e) {

        }
        fila[2] = ingreso.getTipoDeIngreso();
        fila[3] = ingreso.getImporte();
        fila[4] = ingreso.getDescripcion();
        modeloTablaIngreso.addRow(fila);
    }

    private void cargarIngreso() {
        ingreso = (Ingreso) MovimientoCajaFacade.getInstance().buscar((Long) tblIngreso.getValueAt(tblIngreso.getSelectedRow(), 0));
        tfImporte.setText(String.valueOf(ingreso.getImporte()));
        tfDescripcion.setText(ingreso.getDescripcion());
        dpFecha.setDate(ingreso.getFecha());
        try {
            cbTipoIngreso.setSelectedItem(ingreso.getTipoDeIngreso());
        } catch (Exception e) {
        }
        try {
            ftfHora.setText(Comunes.extraerHoraDeFecha(ingreso.getFecha()));
        } catch (Exception e) {
        }
    }

    private void eliminarIngreso() {
        try {
            MovimientoCajaFacade.getInstance().eliminar(ingreso.getId());
            JOptionPane.showMessageDialog(null, "Registro Eliminado");
            cargarTablaIngreso(MovimientoCajaFacade.getInstance().getIngresos());
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }

    private void limpiar() {
        ingreso = new Ingreso();
        Comunes.cargarJCombo(cbTipoIngreso, GenericoFacade.getInstance().find("TipoDeIngreso"));
        tfDescripcion.setText("");
        tfImporte.setText("");
        ftfHora.setText("");
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox cbTipoIngreso;
    private javax.swing.JComboBox cboFiltroTipoIngreso;
    private org.jdesktop.swingx.JXDatePicker dpFecha;
    private javax.swing.JFormattedTextField ftfHora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIngreso;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfImporte;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        caja = CajaFacade.getInstance().getCajaAbierta(sucursal, usuario);
        if (caja == null) {
            Comunes.mensajeError("Es posible que no se haya abierto caja", "No existe caja abierta");
            this.dispose();
        }  //CARGAR TABLA CON Ingresos
        cargarTablaIngreso(MovimientoCajaFacade.getInstance().getIngresos(caja.getFechaInicio()));
        Comunes.setOcultarColumnasJTable(tblIngreso, 0);
        //CARGAR COMBO LISTA EMPLEADOS
        cargarTipoDeIngreso();
        btnAgregar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    private void altaIngreso() {
        if (validarIngreso() && cbTipoIngreso.getSelectedIndex() != -1) {
            try {
                ingreso = new Ingreso();
                ingreso.setTipoDeIngreso((TipoDeIngreso) cbTipoIngreso.getSelectedItem());
//                ingreso.setFecha(dpFecha.getDate());
                ingreso.setFecha(Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()));
                ingreso.setImporte(new BigDecimal(tfImporte.getText()));
                ingreso.setDescripcion(tfDescripcion.getText());
                ingreso.setUsuario(usuario);
                ingreso.setSucursal(sucursal);
                MovimientoCajaFacade.getInstance().alta(ingreso);
                JOptionPane.showMessageDialog(null, "Datos Registrados");
                cargarTablaIngreso(MovimientoCajaFacade.getInstance().getIngresos(caja.getFechaInicio()));
                limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }
        }
    }

    private void cargarParaModificarIngreso() {
        cargarIngreso();
        btnAgregar.setEnabled(false);
        btnModificar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }

    private void modificarIngreso() {
        if (validarIngreso() && cbTipoIngreso.getSelectedIndex() != -1) {
            try {
                ingreso.setTipoDeIngreso((TipoDeIngreso) cbTipoIngreso.getSelectedItem());
                ingreso.setFecha(Comunes.concatenarFechaConHora(dpFecha.getDate(), ftfHora.getText()));
                ingreso.setImporte(new BigDecimal(tfImporte.getText()));
                ingreso.setDescripcion(tfDescripcion.getText());
                ingreso.setUsuario(usuario);
                MovimientoCajaFacade.getInstance().modificar(ingreso);
                JOptionPane.showMessageDialog(null, "Datos modificados!!!");
                cargarTablaIngreso(MovimientoCajaFacade.getInstance().getIngresos());
                limpiar();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error: " + e);
            }
        }

    }

    private void filtrarIngresos() {
        if (cboFiltroTipoIngreso.getSelectedIndex() > 0) {
            cargarIngresos(MovimientoCajaFacade.getInstance().getIngresosPorTipo((TipoDeIngreso) cboFiltroTipoIngreso.getSelectedItem(), caja.getFechaInicio()));
        } else {
            cargarIngresos(MovimientoCajaFacade.getInstance().getIngresos(caja.getFechaInicio()));
        }

    }

}
