/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.articulo.Articulo;
import entidades.caja.PlanTarjeta;
import entidades.caja.TarjetaDeCredito;
import facade.PlanTarjetaFacade;
import facade.SubCategoriaFacade;
import facade.TarjetaDeCreditoFacade;
import facade.UnidadMedidaFacade;
import includes.Comunes;
import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author vouilloz
 */
public class DiagPlanTarjeta extends javax.swing.JDialog {

    private String tipoOperacion;
    private PlanTarjeta planTarjeta;

    /**
     * Creates new form DiagPlanTarjeta
     */
    public DiagPlanTarjeta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public DiagPlanTarjeta(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    public DiagPlanTarjeta(java.awt.Frame parent, boolean modal, String tipoOperacion, PlanTarjeta plan) {
        super(parent, modal);
        initComponents();
        this.planTarjeta = plan;
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbTarjeta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        tfCoeficiente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        checkVale = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.jPanel1.border.title"))); // NOI18N

        cbTarjeta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.jLabel2.text")); // NOI18N

        tfDescripcion.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.tfDescripcion.text")); // NOI18N

        tfCoeficiente.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.tfCoeficiente.text")); // NOI18N
        tfCoeficiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCoeficienteKeyTyped(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.jLabel3.text")); // NOI18N

        jButton1.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        checkVale.setText(org.openide.util.NbBundle.getMessage(DiagPlanTarjeta.class, "DiagPlanTarjeta.checkVale.text")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbTarjeta, 0, 347, Short.MAX_VALUE)
                            .addComponent(tfDescripcion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tfCoeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkVale, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCoeficiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(checkVale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        aceptar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tfCoeficienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCoeficienteKeyTyped
        Comunes.soloNumerosSinComa(tfCoeficiente, evt);
    }//GEN-LAST:event_tfCoeficienteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagPlanTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagPlanTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagPlanTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagPlanTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagPlanTarjeta dialog = new DiagPlanTarjeta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbTarjeta;
    private javax.swing.JCheckBox checkVale;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfCoeficiente;
    private javax.swing.JTextField tfDescripcion;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Plan");
        Comunes.cargarJCombo(cbTarjeta, TarjetaDeCreditoFacade.getInstance().getTodos());
        if (tipoOperacion.equals("Modificación")) {
            cargarDatosPlan();
        }
    }

    private void cargarDatosPlan() {
        try {
            tfDescripcion.setText(planTarjeta.getDescripcion());
        } catch (Exception e) {

        }
        try {
            tfCoeficiente.setText(String.valueOf(planTarjeta.getCoeficiente()));
        } catch (Exception e) {

        }
        try {
            cbTarjeta.setSelectedItem(planTarjeta.getTarjetaDeCredito());
        } catch (Exception e) {

        }
        try {
            checkVale.setSelected(planTarjeta.getEsVale());
        } catch (Exception e) {
        }
    }

    private void aceptar() {
        if (tipoOperacion.equals("Alta")) {
            if (validarPlan()) {
                planTarjeta = new PlanTarjeta();
                planTarjeta.setDescripcion(tfDescripcion.getText().toUpperCase());
                planTarjeta.setCoeficiente(new BigDecimal(tfCoeficiente.getText()));
                planTarjeta.setTarjetaDeCredito((TarjetaDeCredito) cbTarjeta.getSelectedItem());
                planTarjeta.setEsVale(checkVale.isSelected());
                PlanTarjetaFacade.getInstance().alta(planTarjeta);
                JOptionPane.showMessageDialog(this, "Plan Agregado!");
                this.dispose();

            }

        } else if (tipoOperacion.equals("Modificación")) {
            if (validarPlan()) {
                planTarjeta.setDescripcion(tfDescripcion.getText().toUpperCase());
                planTarjeta.setCoeficiente(new BigDecimal(tfCoeficiente.getText()));
                planTarjeta.setTarjetaDeCredito((TarjetaDeCredito) cbTarjeta.getSelectedItem());
                planTarjeta.setEsVale(checkVale.isSelected());
                PlanTarjetaFacade.getInstance().modificar(planTarjeta);
                JOptionPane.showMessageDialog(this, "Plan Modificado!");
                this.dispose();

            }
        }
    }

    private boolean validarPlan() {
        //boolean flag=Boolean.TRUE;
        if (tfDescripcion.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El plan debe tener una Descripcion", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (tfCoeficiente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe especificar un coeficiente", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
}
