/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Caja;

import entidades.caja.CuentaCorriente;
import entidades.cliente.Cliente;
import facade.ClienteFacade;
import facade.CuentaCorrienteFacade;
import includes.Comunes;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class diagCobroCCorriente extends javax.swing.JDialog {

    /**
     * Creates new form diagCobroCCorriente
     */
    public BigDecimal aPagarCuentaCorriente;
    private final BigDecimal monto;
    private final Cliente cliente;
    private CuentaCorriente cuentaCorriente;
    private BigDecimal saldoCuentaCorriente;

    public BigDecimal getaPagarCuentaCorriente() {
        return aPagarCuentaCorriente;
    }

    public CuentaCorriente getCuentaCorriente() {
        return cuentaCorriente;
    }

    public diagCobroCCorriente(java.awt.Frame parent, boolean modal, BigDecimal monto, Cliente cliente) {
        super(parent, modal);
        initComponents();
        this.monto = monto;
        this.cliente = cliente;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfSaldo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfImporteAPagarCC = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfSaldoCuentaCorriente = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.title")); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.jPanel6.border.title"))); // NOI18N

        jLabel14.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.jLabel14.text")); // NOI18N

        jLabel15.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.jLabel15.text")); // NOI18N

        tfSaldo.setEditable(false);
        tfSaldo.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.tfSaldo.text")); // NOI18N

        jLabel17.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.jLabel17.text")); // NOI18N

        tfImporteAPagarCC.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.tfImporteAPagarCC.text")); // NOI18N
        tfImporteAPagarCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfImporteAPagarCCActionPerformed(evt);
            }
        });
        tfImporteAPagarCC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfImporteAPagarCCKeyTyped(evt);
            }
        });

        jLabel18.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.jLabel18.text")); // NOI18N

        tfSaldoCuentaCorriente.setEditable(false);
        tfSaldoCuentaCorriente.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.tfSaldoCuentaCorriente.text")); // NOI18N

        tfCliente.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.tfCliente.text")); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfImporteAPagarCC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfSaldoCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(tfSaldoCuentaCorriente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tfSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tfImporteAPagarCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 29, Short.MAX_VALUE))
        );

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/accept.png"))); // NOI18N
        btnAceptar.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.btnAceptar.text")); // NOI18N
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnCancelar.setText(org.openide.util.NbBundle.getMessage(diagCobroCCorriente.class, "diagCobroCCorriente.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        aceptar();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void tfImporteAPagarCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfImporteAPagarCCActionPerformed
        // TODO add your handling code here:
        btnAceptar.requestFocus();
    }//GEN-LAST:event_tfImporteAPagarCCActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void tfImporteAPagarCCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfImporteAPagarCCKeyTyped
        Comunes.soloNumeros(tfImporteAPagarCC, evt);
    }//GEN-LAST:event_tfImporteAPagarCCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diagCobroCCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diagCobroCCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diagCobroCCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diagCobroCCorriente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                diagCobroCCorriente dialog = new diagCobroCCorriente(new javax.swing.JFrame(), true, new BigDecimal("0.0"), new Cliente() {
                });
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfImporteAPagarCC;
    private javax.swing.JTextField tfSaldo;
    private javax.swing.JTextField tfSaldoCuentaCorriente;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        tfCliente.setEditable(false);
        tfCliente.setText(cliente.toString());
        cuentaCorriente = CuentaCorrienteFacade.getInstance().getCuentaCliente(cliente);
        //tfSaldo.setText(new DecimalFormat("0.00").format(monto));
        tfSaldo.setText(monto.toString());
        //tfImporteAPagarCC.setText(new DecimalFormat("0.00").format(monto));
        tfImporteAPagarCC.setText(monto.toString());
        tfImporteAPagarCC.requestFocus();
    }

    private void aceptar() {
        if (validar()) {
            cuentaCorriente=new CuentaCorriente();
            aPagarCuentaCorriente = BigDecimal.valueOf(Double.parseDouble(tfImporteAPagarCC.getText().replace(",", ".")));
            cuentaCorriente.setImporteCtaCte(aPagarCuentaCorriente);
            cuentaCorriente.setSaldo(aPagarCuentaCorriente);
            cuentaCorriente.setFecha(Comunes.obtenerFechaActualDesdeDB());
            cuentaCorriente.setCliente(cliente);
            this.dispose();
        }
    }

    private boolean validar() {
        if (tfImporteAPagarCC.getText().isEmpty() && !Comunes.validarBigDecimal(tfImporteAPagarCC.getText())) {
            JOptionPane.showMessageDialog(null, "debe cargar un importe a pagar");
            tfImporteAPagarCC.requestFocus();
            return false;
        }
        if (monto.subtract(BigDecimal.valueOf(Double.parseDouble(tfImporteAPagarCC.getText().replace(",", ".")))).signum()==-1) {
            JOptionPane.showMessageDialog(null, "Importe a pagar mayor que el saldo");
            tfImporteAPagarCC.requestFocus();
            return false;
        }
//        if (saldoCuentaCorriente.subtract(new BigDecimal(tfImporteAPagarCC.getText())).signum() < 0) {
//            JOptionPane.showMessageDialog(null, "no posee saldo suficiente");
//            tfImporteAPagarCC.requestFocus();
//            return false;
//        }
        return true;
    }
}
