/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 * comentario
 */

/*
 * ArticuloAlta.java
 *
 * Created on 12/10/2009, 14:29:17
 */
package vista.usuarios;

import entidades.Sucursal;
import entidades.usuario.Grupo;
import entidades.usuario.Usuario;
import facade.GrupoFacade;
import facade.ProvinciaFacade;
import facade.SucursalFacade;
import facade.UsuarioFacade;
import includes.Comunes;
import includes.SHA1;
import includes.SuperInternalFrame;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public class DiagUsuarioModificacion extends javax.swing.JDialog {

    // Atributos    
//    UsuarioFacade usuarioFacade = new UsuarioFacade();
    Usuario usuario;
    SHA1 sha1 = new SHA1();
    private String tipoOperacion;

    /** Creates new form ArticuloAlta */
    public DiagUsuarioModificacion() {
        initComponents();
    }

   
    
    
    public DiagUsuarioModificacion(java.awt.Frame parent, boolean modal, String tipoOperacion, Usuario usuario) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAgregarArticuloNuevo = new javax.swing.JLabel();
        jXPanel6 = new org.jdesktop.swingx.JXPanel();
        lbNombreCompleto = new javax.swing.JLabel();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        tfNombreCompleto = new javax.swing.JTextField();
        lbNombreUsuario = new javax.swing.JLabel();
        tfNombreUsuario = new javax.swing.JTextField();
        lbContrasena = new javax.swing.JLabel();
        passContrasena = new javax.swing.JPasswordField();
        cboGrupo = new javax.swing.JComboBox();
        lbGrupo = new javax.swing.JLabel();
        jXPanel4 = new org.jdesktop.swingx.JXPanel();
        tfBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListClientes = new javax.swing.JList();
        lbContrasena1 = new javax.swing.JLabel();
        passConfirmaContrasena = new javax.swing.JPasswordField();
        btnEliminar = new javax.swing.JButton();

        setTitle("Modificar Usuario");

        lbAgregarArticuloNuevo.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        lbAgregarArticuloNuevo.setText("Modificar Usuario");

        jXPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbNombreCompleto.setText("Nombre Completo");

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        btGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btGuardarKeyPressed(evt);
            }
        });

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        btSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btSalirKeyPressed(evt);
            }
        });

        tfNombreCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfNombreCompletoKeyReleased(evt);
            }
        });

        lbNombreUsuario.setText("Nombre de Usuario");

        tfNombreUsuario.setEnabled(false);

        lbContrasena.setText("Contraseña");

        lbGrupo.setText("Grupo");

        jXPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda"));

        tfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfBuscarKeyReleased(evt);
            }
        });

        jListClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListClientesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListClientes);

        javax.swing.GroupLayout jXPanel4Layout = new javax.swing.GroupLayout(jXPanel4);
        jXPanel4.setLayout(jXPanel4Layout);
        jXPanel4Layout.setHorizontalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jXPanel4Layout.setVerticalGroup(
            jXPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel4Layout.createSequentialGroup()
                .addComponent(tfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbContrasena1.setText("Confirma Contraseña");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel6Layout = new javax.swing.GroupLayout(jXPanel6);
        jXPanel6.setLayout(jXPanel6Layout);
        jXPanel6Layout.setHorizontalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addComponent(jXPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jXPanel6Layout.createSequentialGroup()
                                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNombreCompleto)
                                    .addComponent(lbContrasena)
                                    .addComponent(lbNombreUsuario)
                                    .addComponent(lbContrasena1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfNombreCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                                    .addGroup(jXPanel6Layout.createSequentialGroup()
                                        .addGap(132, 132, 132)
                                        .addComponent(tfNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                                    .addComponent(passContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)
                                    .addComponent(passConfirmaContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE)))
                            .addGroup(jXPanel6Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(lbGrupo)
                                .addGap(18, 18, 18)
                                .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jXPanel6Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jXPanel6Layout.setVerticalGroup(
            jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jXPanel6Layout.createSequentialGroup()
                        .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombreCompleto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNombreUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbContrasena))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passConfirmaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbContrasena1))
                .addGap(5, 5, 5)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrupo)
                    .addComponent(cboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jXPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAgregarArticuloNuevo)
                    .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbAgregarArticuloNuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSalirKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_UP)) {
            if (btGuardar.isEnabled()) {
                btGuardar.requestFocus();
            } else {
                tfNombreCompleto.requestFocus();
            }
        } else if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.dispose();
        }
}//GEN-LAST:event_btSalirKeyPressed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_btSalirActionPerformed

    private void btGuardarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btGuardarKeyPressed
        if ((evt.getKeyCode() == KeyEvent.VK_DOWN)) {
            btSalir.requestFocus();
        } else if ((evt.getKeyCode() == KeyEvent.VK_UP)) {
            tfNombreCompleto.requestFocus();
        } else if ((evt.getKeyCode() == KeyEvent.VK_ENTER)) {
            cargarDatosUsuario();
            UsuarioFacade.getInstance().modificar(usuario);
            this.dispose();
        }
}//GEN-LAST:event_btGuardarKeyPressed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        cargarDatosUsuario();
        UsuarioFacade.getInstance().modificar(usuario);
        this.dispose();
}//GEN-LAST:event_btGuardarActionPerformed

    private void tfNombreCompletoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNombreCompletoKeyReleased
        btGuardar.setEnabled(true);
    }//GEN-LAST:event_tfNombreCompletoKeyReleased

    private void tfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBuscarKeyReleased
        filtrarListado();
}//GEN-LAST:event_tfBuscarKeyReleased

    private void jListClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListClientesValueChanged
        usuario = (Usuario) jListClientes.getSelectedValue();
        cargarTextFieldsUsuario();
}//GEN-LAST:event_jListClientesValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminarUsuario();
    }//GEN-LAST:event_btnEliminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JComboBox cboGrupo;
    private javax.swing.JList jListClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXPanel jXPanel4;
    private org.jdesktop.swingx.JXPanel jXPanel6;
    private javax.swing.JLabel lbAgregarArticuloNuevo;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbContrasena1;
    private javax.swing.JLabel lbGrupo;
    private javax.swing.JLabel lbNombreCompleto;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JPasswordField passConfirmaContrasena;
    private javax.swing.JPasswordField passContrasena;
    private javax.swing.JTextField tfBuscar;
    private javax.swing.JTextField tfNombreCompleto;
    private javax.swing.JTextField tfNombreUsuario;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        tfBuscar.requestFocus();
        cargarComboBoxGrupo();
        filtrarListado();
    }

    public void limpiarTextFields() {
        tfNombreCompleto.setText("");
        tfNombreUsuario.setText("");
        passContrasena.setText("");
    }

    public void cerrarVentana() {
        this.dispose();
    }

    private void reiniciarListas() {
    //    UsuarioFacade usuFa = new UsuarioFacade();
        Comunes.cargarJList(jListClientes, UsuarioFacade.getInstance().listarTodosUsuarios());
    }

    private void cargarComboBoxGrupo() {
        Comunes.cargarJCombo(cboGrupo, GrupoFacade.getInstance().listarGrupos());
    }

    public void cargarDatosUsuario() {
        usuario.setNombreCompleto(tfNombreCompleto.getText());
        usuario.setNombreUsuario(tfNombreUsuario.getText());
        String password = new String(passContrasena.getPassword());
        String confirmaPassword = new String(passConfirmaContrasena.getPassword());
        if (!password.equals("")) {
            if (password.equals(confirmaPassword)) {
                try {
                    usuario.setContrasena(sha1.getHash(new String(passContrasena.getPassword())));
                } catch (NoSuchAlgorithmException ex) {
                    JOptionPane.showMessageDialog(this, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden, no se cambiará", "Error de Confirmación de Contraseña", JOptionPane.ERROR_MESSAGE);
                passConfirmaContrasena.setText("");
                passContrasena.setText("");
            }
        }
        usuario.setGrupo((Grupo) cboGrupo.getSelectedItem());
    }

    private void cargarTextFieldsUsuario() {
        tfNombreCompleto.requestFocus();
        tfNombreCompleto.setText(usuario.getNombreCompleto());
        tfNombreUsuario.setText(usuario.getNombreUsuario());
        cargarComboBoxGrupo();
        cboGrupo.setSelectedItem(usuario.getGrupo());
    }

    private void filtrarListado() {
        List<Usuario> listUsuario = UsuarioFacade.getInstance().listarUsuarios(tfBuscar.getText());
        DefaultListModel modeloLista = new DefaultListModel();
        for (int i = 0; i < listUsuario.size(); i++) {
            modeloLista.addElement(listUsuario.get(i));
        }
        jListClientes.setModel(modeloLista);
    }
    
        private void eliminarUsuario() {
//            UsuarioFacade usuFa = new UsuarioFacade();
        if (jListClientes.getSelectedIndex() != -1) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el usuario seleccionado de la base de datos?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                UsuarioFacade.getInstance().eliminar(((Usuario) jListClientes.getSelectedValue()).getId());
                JOptionPane.showMessageDialog(null, "Usuario eliminado");
                limpiarTextFields();
                reiniciarListas();
                Comunes.cargarJList(jListClientes, UsuarioFacade.getInstance().listarTodosUsuarios());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario para eliminar");
        }
    }

}
