/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.promocion;

import entidades.Sucursal;
import entidades.promocion.Promocion;
import facade.PromocionFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author hugo
 */
public class DiagAdminPromociones extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private ModeloTablaNoEditable modeloTablaPromocions;
    private Sucursal sucursal;

    public DiagAdminPromociones(java.awt.Frame parent, boolean modal, Sucursal sucursal) {
        super(parent, modal);
        this.sucursal = sucursal;
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPromociones = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        tfPromocion = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jPanel3.border.title"))); // NOI18N

        tblPromociones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPromociones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPromocionesMouseClicked(evt);
            }
        });
        tblPromociones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblPromocionesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblPromociones);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jLabel5.text")); // NOI18N

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        jbNuevo.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jbNuevo.text")); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        tfPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPromocionActionPerformed(evt);
            }
        });

        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar2.png"))); // NOI18N
        jbBuscar.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jbBuscar.text")); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        jButton2.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        jButton3.setText(org.openide.util.NbBundle.getMessage(DiagAdminPromociones.class, "DiagAdminPromociones.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(jbBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jbNuevo)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(102, 102, 102))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarPromocion();
        cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        modificarPromocion();
        cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        if (!tfPromocion.getText().isEmpty()) {
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorDescripcion(tfPromocion.getText(), sucursal));
        } else {
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        agregarNuevoPromocion();
        cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void tfPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPromocionActionPerformed
        if (!tfPromocion.getText().isEmpty()) {
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorDescripcion(tfPromocion.getText(), sucursal));
        } else {
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
        }
    }//GEN-LAST:event_tfPromocionActionPerformed

    private void tblPromocionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPromocionesMouseClicked
        if (evt.getClickCount() == 2) {
            modificarPromocion();
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
        }
    }//GEN-LAST:event_tblPromocionesMouseClicked

    private void tblPromocionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblPromocionesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            modificarPromocion();
            cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
        }
    }//GEN-LAST:event_tblPromocionesKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTable tblPromociones;
    private javax.swing.JTextField tfPromocion;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Administracion de Promociones");
        cargarTablaPromociones(PromocionFacade.getInstance().buscarPorSucursal(sucursal));
    }

    private void cargarTablaPromociones(List<Promocion> promociones) {
        modeloTablaPromocions = new ModeloTablaNoEditable();
        cargarEncabezadosTablaPromocions(modeloTablaPromocions);
        configurarTabla(tblPromociones);
        try {
            cargarPromocions(promociones);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaPromocions(ModeloTablaNoEditable modeloTablaPromocions) {
        modeloTablaPromocions.addColumn("Id");
        modeloTablaPromocions.addColumn("Nombre");
        modeloTablaPromocions.addColumn("Tipo");
        modeloTablaPromocions.addColumn("Desde");
        modeloTablaPromocions.addColumn("Hasta");
        modeloTablaPromocions.addColumn("Activa");
        modeloTablaPromocions.addColumn("Prioridad");
        modeloTablaPromocions.addColumn("Sucursal");
        tblPromociones.setModel(modeloTablaPromocions);
        Comunes.setOcultarColumnasJTable(tblPromociones, 0);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarPromocions(List<Promocion> promociones) {
        try {
            modeloTablaPromocions = new ModeloTablaNoEditable();
            cargarEncabezadosTablaPromocions(modeloTablaPromocions);
            for (Promocion articulo : promociones) {
                cargarPromocion(articulo);
            }

            tblPromociones.setModel(modeloTablaPromocions);
        } catch (Exception ex) {
            Logger.getLogger(DiagAdminPromociones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarPromocion(Promocion promocion) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Object[] fila = new Object[8];
        fila[0] = promocion.getId();
        try {
            fila[1] = promocion.getNombre();
        } catch (Exception e) {
        }
        try {
            fila[2] = promocion.isEsPorPrecio() ? "Precio" : "Porcentaje";
        } catch (Exception e) {
        }
        try {
            fila[3] = dateFormat.format(promocion.getFechaInicio());
        } catch (Exception e) {
        }
        try {
            fila[4] = dateFormat.format(promocion.getFechaFin());
        } catch (Exception e) {
        }
        try {
            fila[5] = promocion.isHabilitada() ? "SI" : "NO";
        } catch (Exception e) {
        }
        try {
            fila[6] = promocion.getPrioridad();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Exception: " + e);
        }
        try {
            fila[7] = promocion.getSucursal();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Exception: " + e);
        }
        modeloTablaPromocions.addRow(fila);
    }

    private void modificarPromocion() {
        if (tblPromociones.getSelectedRow() != -1) {
            Promocion promocion = PromocionFacade.getInstance().buscar((Long) tblPromociones.getValueAt(tblPromociones.getSelectedRow(), 0));
            DiagPromocion diagPromocion = new DiagPromocion(null, true, "Modificación", promocion, sucursal);
            diagPromocion.setLocation(Comunes.centrarDialog(diagPromocion));
            diagPromocion.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Promocion");
        }

    }

    private void eliminarPromocion() {
        if (tblPromociones.getSelectedRow() != -1) {
            int i = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el Registro seleccionado?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
            if (i == 0) {
                PromocionFacade.getInstance().eliminar((Long) tblPromociones.getValueAt(tblPromociones.getSelectedRow(), 0));
                JOptionPane.showMessageDialog(null, "Registro eliminado");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un Promocion");
        }
    }

    private void agregarNuevoPromocion() {
        DiagPromocion diagPromocion = new DiagPromocion(null, true, "Alta", sucursal);
        diagPromocion.setLocation(Comunes.centrarDialog(diagPromocion));
        diagPromocion.setVisible(true);
    }

}
