/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventas;

import entidades.Configuracion;
import entidades.Sucursal;
import entidades.articulo.Articulo;
import entidades.cliente.Organismo;
import entidades.cliente.Persona;
import entidades.persona.DocumentoIdentidad;
import entidades.persona.TipoDocumento;
import entidades.usuario.Usuario;
import entidades.venta.Venta;
import entidades.venta.VentaArticulo;
import facade.ArticuloFacade;
import facade.ClienteFacade;
import facade.ConfiguracionFacade;
import facade.SucursalFacade;
import facade.TipoDocumentoFacade;
import facade.UsuarioFacade;
import facade.VentaFacade;
import includes.ExportarExcel;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author hugo
 */
public class DiagExportarImportarVentas extends javax.swing.JDialog {

    /**
     * Creates new form DiagClienteGenerico
     */
    private String tipoOperacion;
    private javax.swing.JTextField jTextField;
    private ModeloTablaNoEditable modeloTablaVentas;
    private Vector headers = new Vector();
    private Vector data = new Vector();
    private Venta venta;
    private VentaArticulo ventaArticulo;
    private List<VentaArticulo> listaVentaArticulos;
    private Articulo articulo;

    private Persona persona;
    private Organismo organismo;

    private DocumentoIdentidad documento;
    private TipoDocumento tipodoc;

    private Sucursal sucursal;
    private Usuario usuario;

    private int AuxTicket, AuxSucursal;

    public DiagExportarImportarVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicializarComponentes();
    }

    public DiagExportarImportarVentas(java.awt.Frame parent, boolean modal, String tipoOperacion) {
        super(parent, modal);
        initComponents();
        this.tipoOperacion = tipoOperacion;
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgCodDesc = new javax.swing.ButtonGroup();
        btnCerrar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();
        btnExportarArt = new javax.swing.JButton();
        btnImportarArt = new javax.swing.JButton();
        btnGuardarCambios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnCerrar.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarVentas.class, "DiagExportarImportarVentas.btnCerrar.text")); // NOI18N
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagExportarImportarVentas.class, "DiagExportarImportarVentas.jPanel3.border.title"))); // NOI18N

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Anulado", "Descuento", "Fecha", "Monto", "Numero Ticket", "Apellido Cli", "Nombre Cli", "Nro Dni", "Tipo Dni", "Razon Social", "CUIL", "Cod Sucursal", "Usu", "CantidadPeso", "PrecioxCatidad", "Precio Cobrado", "Precio Unitario", "Articulo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVentas);

        btnExportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnExportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarVentas.class, "DiagExportarImportarVentas.btnExportarArt.text")); // NOI18N
        btnExportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarArtActionPerformed(evt);
            }
        });

        btnImportarArt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/new_page.png"))); // NOI18N
        btnImportarArt.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarVentas.class, "DiagExportarImportarVentas.btnImportarArt.text")); // NOI18N
        btnImportarArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportarArtActionPerformed(evt);
            }
        });

        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/save.png"))); // NOI18N
        btnGuardarCambios.setText(org.openide.util.NbBundle.getMessage(DiagExportarImportarVentas.class, "DiagExportarImportarVentas.btnGuardarCambios.text")); // NOI18N
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1321, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGuardarCambios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImportarArt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImportarArt, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarCambios)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(584, 584, 584)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCerrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnExportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarArtActionPerformed
        Exportar();
    }//GEN-LAST:event_btnExportarArtActionPerformed

    private void btnImportarArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportarArtActionPerformed
        Importar();
    }//GEN-LAST:event_btnImportarArtActionPerformed

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
        guardarVentas();
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DiagExportarImportarVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DiagExportarImportarVentas dialog = new DiagExportarImportarVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCodDesc;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnExportarArt;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnImportarArt;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        this.setTitle("Exportar/Importar Ventas");
        cargarTablaVentas(VentaFacade.getInstance().getTodos());
        AuxTicket = 0;
        AuxSucursal = 0;
        Configuracion configSucursal = ConfiguracionFacade.getInstance().buscar("sucursal");
        String codSucursal = configSucursal.getValor();
        sucursal = SucursalFacade.getInstance().buscarPorCodigo(codSucursal);
        if (!sucursal.getNombre().toUpperCase().contains("CENTRAL")) {
            btnGuardarCambios.setEnabled(false);
            btnImportarArt.setEnabled(false);
        }
    }

    private void cargarTablaVentas(List<Venta> ventas) {
        modeloTablaVentas = new ModeloTablaNoEditable();
        cargarEncabezadosTablaArticulos(modeloTablaVentas);
        configurarTabla(tblVentas);
        try {
            cargarVentas(ventas);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + ex);
        }
    }

    private void cargarEncabezadosTablaArticulos(ModeloTablaNoEditable modeloTablaArticulos) {
        modeloTablaArticulos.addColumn("Id");
        modeloTablaArticulos.addColumn("Anulado");
        modeloTablaArticulos.addColumn("Descuento");
        modeloTablaArticulos.addColumn("Fecha");
        modeloTablaArticulos.addColumn("Monto");
        modeloTablaArticulos.addColumn("Numero Ticket");
        modeloTablaArticulos.addColumn("Apellido Cli");
        modeloTablaArticulos.addColumn("Nombre Cli");
        modeloTablaArticulos.addColumn("Nro Doc");
        modeloTablaArticulos.addColumn("Tipo Doc");
        modeloTablaArticulos.addColumn("Razon Social");
        modeloTablaArticulos.addColumn("CUIL");
        modeloTablaArticulos.addColumn("Cod Sucursal");
        modeloTablaArticulos.addColumn("Nom Usuario");
        modeloTablaArticulos.addColumn("Cantidad/Peso");
        modeloTablaArticulos.addColumn("PrecioXCantidad");
        modeloTablaArticulos.addColumn("Precio Cobrado");
        modeloTablaArticulos.addColumn("Precio Unitario");
        modeloTablaArticulos.addColumn("Articulo id");
        modeloTablaArticulos.addColumn("Codigo Articulo");
        tblVentas.setModel(modeloTablaVentas);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = (1 * ancho) / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 10));
    }

    private void cargarVentas(List<Venta> ventas) {
        try {
            modeloTablaVentas = new ModeloTablaNoEditable();
            cargarEncabezadosTablaArticulos(modeloTablaVentas);
            for (Venta venta : ventas) {
                for (VentaArticulo va : venta.getVentasArticulos()) {
                    cargarVenta(venta, va);
                }
            }

            tblVentas.setModel(modeloTablaVentas);
            // Comunes.setOcultarColumnasJTable(tblVentas, 0);
        } catch (Exception ex) {
            Logger.getLogger(DiagExportarImportarVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarVenta(Venta venta, VentaArticulo va) {
        // JOptionPane.showMessageDialog(null, "va "+va.getCantidadPeso());
        SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
        Object[] fila = new Object[16];
        fila[0] = venta.getId();
        fila[1] = venta.isAnulado();
        fila[2] = venta.getDescuento();
        if (venta.getFecha() != null) {
            fila[3] = formats.format(venta.getFecha());
        }
        fila[4] = venta.getMonto();
        fila[5] = venta.getNumeroTicket();

        fila[6] = venta.getCliente();
        //   JOptionPane.showMessageDialog(null, "nombre " + persona.getNombre());
        fila[7] = venta.getDniCliente();

        fila[8] = venta.getSucursal().getCodigo();
        fila[9] = venta.getUsuario().getNombreUsuario();
        fila[10] = va.getCantidadPeso().toString();
        fila[11] = va.getPrecio();
        fila[12] = va.getPrecioPromocion();
        fila[13] = va.getPrecioUnitario();
        fila[14] = va.getArticuloDescripcion();
        fila[15] = va.getArticuloCodigo();

        modeloTablaVentas.addRow(fila);
    }

    private void Exportar() {
        new ExportarExcel().crearExcelJtable(tblVentas, "Listado de Ventas");
    }

    private void Importar() {
        JFileChooser jChooser = new JFileChooser(System.getProperty("user.dir"));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos Excel", "xls");
        jChooser.setFileFilter(filter);
        jChooser.showOpenDialog(this);
        File file = jChooser.getSelectedFile();
        if (file == null || !file.getName().endsWith("xls")) {
            JOptionPane.showMessageDialog(null, "Solo se permiten Archivos .xls.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            leerDatosExcel(file);
            List<Integer> columnasNoEditables = new ArrayList<>();
            columnasNoEditables.add(0);
            columnasNoEditables.add(1);
            columnasNoEditables.add(2);
            columnasNoEditables.add(3);
            columnasNoEditables.add(4);
            columnasNoEditables.add(5);
            columnasNoEditables.add(6);
            columnasNoEditables.add(7);
            columnasNoEditables.add(8);
            columnasNoEditables.add(9);
            columnasNoEditables.add(10);
            columnasNoEditables.add(11);
            columnasNoEditables.add(12);
            columnasNoEditables.add(13);
            columnasNoEditables.add(14);
            ModeloTablaNoEditable model = new ModeloTablaNoEditable(data, headers, columnasNoEditables);
            tblVentas.setModel(model);
        }
    }

    void leerDatosExcel(File file) {
        Workbook workbook = null;
        try {
            try {
                workbook = Workbook.getWorkbook(file);
            } catch (IOException ex) {
                System.out.println("Error: " + ex);
            }
            Sheet sheet = workbook.getSheet(0);
            headers.clear();
            for (int i = 0; i < sheet.getColumns(); i++) {
                Cell cell1 = sheet.getCell(i, 0);
                headers.add(cell1.getContents());
            }
            data.clear();
            for (int j = 1; j < sheet.getRows(); j++) {
                Vector d = new Vector();
                for (int i = 0; i < sheet.getColumns(); i++) {
                    Cell cell = sheet.getCell(i, j);
                    d.add(cell.getContents());
                }
                d.add("\n");
                data.add(d);
            }
        } catch (BiffException e) {
            e.printStackTrace();
        }
    }

//    private void guardarVentas() {
//
//        try {
//            for (int i = 0; i < tblVentas.getRowCount(); i++) {
//                //JOptionPane.showMessageDialog(null,"numero ticket y sucursal"+(String) tblVentas.getValueAt(i, 5)+(String) tblVentas.getValueAt(i, 12));
//                //verificamos la existencia de la venta en la base de datos, validamos por numero ticket y sucursal
//                if (!VentaFacade.getInstance().getVentaNumeroTicketSucursal((String) tblVentas.getValueAt(i, 5), (String) tblVentas.getValueAt(i, 12))) {
//                  
//                    
//                    
//                    venta = new Venta();
//                    
//                    
//                    
//                    if (tblVentas.getValueAt(i, 1).equals("true")) {
//                        venta.setAnulado(true);
//                    } else {
//                        venta.setAnulado(false);
//                    }
//
//                    if (tblVentas.getValueAt(i, 2).equals("")) {
//                        System.out.println("entra set descuento");
//                        venta.setDescuento(new BigDecimal((String) tblVentas.getValueAt(i, 2)));
//                    }
//
//                    SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
//                    venta.setFecha(formats.parse((String) tblVentas.getValueAt(i, 3)));
//                    //System.out.println("paso");
//                    venta.setMonto(new BigDecimal((String) tblVentas.getValueAt(i, 4)));
//
//                    venta.setNumeroTicket((String) tblVentas.getValueAt(i, 5));
//
//                    //Si es Persona
//                    if (!tblVentas.getValueAt(i, 8).equals("null")) {
//                    //System.out.println("paso");
//                    //JOptionPane.showMessageDialog(null, "llego");
//                        try {
//                            JOptionPane.showMessageDialog(null, "entro por persona" + ClienteFacade.getInstance().getPersonaXDni((String) tblVentas.getValueAt(i, 8)).getDocumentoIdentidad().getNumero());
//                        } catch (Exception e) {
//                        }
//
//                        persona = new Persona();
//
////Buscamos si existe el cliente persona
//                        if (ClienteFacade.getInstance().getPersonaDni((String) tblVentas.getValueAt(i, 8))) {
//                            //si existe se la setea a persona
//            //                JOptionPane.showMessageDialog(null, "existe persona");
//                            persona = ClienteFacade.getInstance().getPersonaXDni((String) tblVentas.getValueAt(i, 8));
//                        } else {
//                            //sino se la crea
//                            persona.setApellido((String) tblVentas.getValueAt(i, 6));
//                            persona.setNombre((String) tblVentas.getValueAt(i, 7));
//
//                            documento = new DocumentoIdentidad();
//                            documento.setNumero((String) tblVentas.getValueAt(i, 8));
//
//                            //Buscamos si existe tipo de Documento
//                            tipodoc = new TipoDocumento();
//                            if (TipoDocumentoFacade.getInstance().buscarExisteTipo((String) tblVentas.getValueAt(i, 8))) {
//                                //si existe sel le setea
//                                tipodoc = TipoDocumentoFacade.getInstance().buscarPorTipo((String) tblVentas.getValueAt(i, 8));
//                            } else {
//                                //sino se lo crea
//                                tipodoc.setDescripcion((String) tblVentas.getValueAt(i, 9));
//                                TipoDocumentoFacade.getInstance().alta(tipodoc);
//                            }
//
//                            documento.setTipoDocumento(tipodoc);
//                            persona.setDocumentoIdentidad(documento);
//                            ClienteFacade.getInstance().alta(persona);
//                        }
//
//                        venta.setCliente(persona);
//
//                    }
//
//                    //Si es Organismo
//                    if (!tblVentas.getValueAt(i, 11).equals("null")) {
//                        JOptionPane.showMessageDialog(null, "entro por organismo");
//                        try {
//                            JOptionPane.showMessageDialog(null, "entro por Organismo" + ClienteFacade.getInstance().buscarCuitEmpresaObjeto((String) tblVentas.getValueAt(i, 11)).getCUIT());
//                        } catch (Exception e) {
//                            JOptionPane.showMessageDialog(null, "Error: "+e);
//                        }
//                        organismo = new Organismo();
//                        //Buscamos si existe el cliente organismo 
//                        if (ClienteFacade.getInstance().buscarCuitEmpresa((String) tblVentas.getValueAt(i, 11))) {
//                            //si existe se lo setea 
//                            organismo = ClienteFacade.getInstance().buscarCuitEmpresaObjeto((String) tblVentas.getValueAt(i, 11));
//                        } else {
//                            //sino se lo crea
//                            organismo.setCUIT((String) tblVentas.getValueAt(i, 11));
//                            organismo.setRazonSocial((String) tblVentas.getValueAt(i, 10));
//                            ClienteFacade.getInstance().alta(organismo);
//                        }
//
//                        venta.setCliente(organismo);
//                    }
//
//                    //existe sucursal
//                    if (SucursalFacade.getInstance().buscarExisteCodigo((String) tblVentas.getValueAt(i, 12))) {
//                        //buscar y setear sucursal
//                        sucursal = new Sucursal();
//                        sucursal = SucursalFacade.getInstance().buscarPorCodigo((String) tblVentas.getValueAt(i, 12));
//                    }
//
//                    //existe usuario
//                    UsuarioFacade uF = new UsuarioFacade();
//                    if (uF.buscarExisteUsuario((String) tblVentas.getValueAt(i, 13))) {
//                        //buscar y setear Usuario
//                        usuario = new Usuario();
//                        usuario = uF.buscarPorNombre((String) tblVentas.getValueAt(i, 13));
//                    }
//                    venta.setSucursal(sucursal);
//                    venta.setUsuario(usuario);
//                    VentaFacade.getInstance().alta(venta);
//                }
//                
//            }
//            JOptionPane.showMessageDialog(null, "Importacion de ventas Realizado");
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "ERROR" + e);
//        }
//
//    }
    private void guardarVentas() {
        //JOptionPane.showMessageDialog(null, "entro gusrdarVentas");
        try {
            for (int i = 0; i < tblVentas.getRowCount(); i++) {
                //JOptionPane.showMessageDialog(null,"numero ticket y sucursal"+(String) tblVentas.getValueAt(i, 5)+(String) tblVentas.getValueAt(i, 12));
                //verificamos la existencia de la venta en la base de datos, validamos por numero ticket y sucursal

                //si no existe la venta la creamos
                if (!VentaFacade.getInstance().getVentaNumeroTicketSucursal((String) tblVentas.getValueAt(i, 5), (String) tblVentas.getValueAt(i, 12))) {
                    //  JOptionPane.showMessageDialog(null, "entra por no existe venta");

                    venta = new Venta();
                    ventaArticulo = new VentaArticulo();
                    articulo = new Articulo();
                    listaVentaArticulos = new ArrayList<>();

                    if (tblVentas.getValueAt(i, 1).equals("true")) {
                        venta.setAnulado(true);
                    } else {
                        venta.setAnulado(false);
                    }

                    if (tblVentas.getValueAt(i, 2).equals("")) {
                        System.out.println("entra set descuento");
                        venta.setDescuento(new BigDecimal((String) tblVentas.getValueAt(i, 2)));
                    }

                    SimpleDateFormat formats = new SimpleDateFormat("dd/MM/yyyy");
                    venta.setFecha(formats.parse((String) tblVentas.getValueAt(i, 3)));
                    //System.out.println("paso");
                    venta.setMonto(new BigDecimal((String) tblVentas.getValueAt(i, 4)));

                    venta.setNumeroTicket((int) tblVentas.getValueAt(i, 5));

                    //Si es Persona
                    if (!tblVentas.getValueAt(i, 8).equals("null")) {
                        //System.out.println("paso");
                        //JOptionPane.showMessageDialog(null, "llego");

                        persona = new Persona();

                        //Buscamos si existe el cliente persona
                        if (ClienteFacade.getInstance().getPersonaDni((String) tblVentas.getValueAt(i, 8))) {
                            //si existe se la setea a persona
                            //                JOptionPane.showMessageDialog(null, "existe persona");
                            persona = ClienteFacade.getInstance().getPersonaXDni((String) tblVentas.getValueAt(i, 8));
                        } else {
                            //sino se la crea
                            persona.setApellido((String) tblVentas.getValueAt(i, 6));
                            persona.setNombre((String) tblVentas.getValueAt(i, 7));

                            documento = new DocumentoIdentidad();
                            documento.setNumero((String) tblVentas.getValueAt(i, 8));

                            //Buscamos si existe tipo de Documento
                            tipodoc = new TipoDocumento();
                            if (TipoDocumentoFacade.getInstance().buscarExisteTipo((String) tblVentas.getValueAt(i, 8))) {
                                //si existe sel le setea
                                tipodoc = TipoDocumentoFacade.getInstance().buscarPorTipo((String) tblVentas.getValueAt(i, 8));
                            } else {
                                //sino se lo crea
                                tipodoc.setDescripcion((String) tblVentas.getValueAt(i, 9));
                                TipoDocumentoFacade.getInstance().alta(tipodoc);
                            }

                            documento.setTipoDocumento(tipodoc);
                            persona.setDocumentoIdentidad(documento);
                            ClienteFacade.getInstance().alta(persona);
                        }

                        venta.setCliente(persona.toString());
                        venta.setDniCliente(persona.getDocumentoIdentidad().getNumero());
                        venta.setEsPersona(true);

                    }

                    //Si es Organismo
                    if (!tblVentas.getValueAt(i, 11).equals("null")) {
                        //JOptionPane.showMessageDialog(null, "entro por organismo");

                        organismo = new Organismo();
                        //Buscamos si existe el cliente organismo 
                        if (ClienteFacade.getInstance().buscarCuitEmpresa((String) tblVentas.getValueAt(i, 11))) {
                            //si existe se lo setea 
                            organismo = ClienteFacade.getInstance().buscarCuitEmpresaObjeto((String) tblVentas.getValueAt(i, 11));
                        } else {
                            //sino se lo crea
                            organismo.setCUIT((String) tblVentas.getValueAt(i, 11));
                            organismo.setRazonSocial((String) tblVentas.getValueAt(i, 10));
                            ClienteFacade.getInstance().alta(organismo);
                        }

                        venta.setCliente(organismo.getRazonSocial());
                        venta.setDniCliente(organismo.getCUIT());
                        venta.setEsPersona(false);
                    }

                    //existe sucursal
                    if (SucursalFacade.getInstance().buscarExisteCodigo((String) tblVentas.getValueAt(i, 12))) {
                        //buscar y setear sucursal
                        sucursal = new Sucursal();
                        sucursal = SucursalFacade.getInstance().buscarPorCodigo((String) tblVentas.getValueAt(i, 12));
                    }

                    //existe usuario
                    //UsuarioFacade uF = new UsuarioFacade();
                    if (UsuarioFacade.getInstance().buscarExisteUsuario((String) tblVentas.getValueAt(i, 13))) {
                        //buscar y setear Usuario
                        usuario = new Usuario();
                        usuario = UsuarioFacade.getInstance().buscarPorNombre((String) tblVentas.getValueAt(i, 13));
                    }
                    venta.setSucursal(sucursal);
                    venta.setUsuario(usuario);

                    //Carga de ventaArticulo y se lo setea a venta
                    //JOptionPane.showMessageDialog(null, "entro setear venta articulo");
                    ventaArticulo.setCantidadPeso(new BigDecimal((String) tblVentas.getValueAt(i, 14)));
                    ventaArticulo.setPrecio(new BigDecimal((String) tblVentas.getValueAt(i, 15)));
                    ventaArticulo.setPrecioPromocion(new BigDecimal((String) tblVentas.getValueAt(i, 16)));
                    ventaArticulo.setPrecioUnitario(new BigDecimal((String) tblVentas.getValueAt(i, 17)));

                    //traer y setear el articulo
                    //JOptionPane.showMessageDialog(null, "entro al try" + Long.parseLong(String.valueOf(tblVentas.getValueAt(i, 18))));
                    articulo = ArticuloFacade.getInstance().buscar(Long.parseLong(String.valueOf(tblVentas.getValueAt(i, 18))));
                    ventaArticulo.setArticuloDescripcion(articulo.getDescripcionReducida());
                    ventaArticulo.setArticuloCodigo(articulo.getCodigoBarra());
                    listaVentaArticulos.add(ventaArticulo);
                    //JOptionPane.showMessageDialog(null, "carga la lista ventaArticulos");

                    venta.setVentasArticulos(listaVentaArticulos);

                    VentaFacade.getInstance().alta(venta);

                    AuxTicket = Integer.parseInt(String.valueOf(tblVentas.getValueAt(i, 5)));
                    AuxSucursal = Integer.parseInt(String.valueOf(tblVentas.getValueAt(i, 12)));
                    // JOptionPane.showMessageDialog(null, "llego al final");
                } //entra por el else si ya existe la venta en BD
                else {
                    //JOptionPane.showMessageDialog(null, "salio por el else");
                    if (AuxTicket == Integer.parseInt(String.valueOf(tblVentas.getValueAt(i, 5))) && AuxSucursal == Integer.parseInt(String.valueOf(tblVentas.getValueAt(i, 12)))) {
                        // JOptionPane.showMessageDialog(null, "Entro por AuxTicket Auxsucuersal iguales");
                        //Traer venta segun ticket y sucursal y setear venta articulo
                        //Carga de ventaArticulo y se lo setea a venta
                        ventaArticulo = new VentaArticulo();
                        articulo = new Articulo();
                        //JOptionPane.showMessageDialog(null, "entro setear venta articulo");
                        ventaArticulo.setCantidadPeso(new BigDecimal((String) tblVentas.getValueAt(i, 14)));
                        ventaArticulo.setPrecio(new BigDecimal((String) tblVentas.getValueAt(i, 15)));
                        ventaArticulo.setPrecioPromocion(new BigDecimal((String) tblVentas.getValueAt(i, 16)));
                        ventaArticulo.setPrecioUnitario(new BigDecimal((String) tblVentas.getValueAt(i, 17)));

                        //traer y setear el articulo
                        //JOptionPane.showMessageDialog(null, "entro al try" + Long.parseLong(String.valueOf(tblVentas.getValueAt(i, 18))));
                        articulo = ArticuloFacade.getInstance().buscar(Long.parseLong(String.valueOf(tblVentas.getValueAt(i, 18))));
                        ventaArticulo.setArticuloDescripcion(articulo.getDescripcionReducida());
                        ventaArticulo.setArticuloCodigo(articulo.getCodigoBarra());
                        listaVentaArticulos.add(ventaArticulo);
                        //JOptionPane.showMessageDialog(null, "carga la lista ventaArticulos");

                        venta.setVentasArticulos(listaVentaArticulos);

                        VentaFacade.getInstance().modificar(venta);
                    } else {
                        //JOptionPane.showMessageDialog(null, "Cambia a nueva venta, inicializa en cero AuxTicket y Auxsucursal");
                        AuxTicket = 0;
                        AuxSucursal = 0;
                        listaVentaArticulos = new ArrayList<>();
                    }
                }

            }
            JOptionPane.showMessageDialog(null, "Importacion de ventas Realizado");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR" + e);
        }

    }

}
