/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.ventas;

import entidades.Sucursal;
import entidades.cliente.Organismo;
import entidades.cliente.Persona;
import entidades.usuario.Usuario;
import entidades.venta.OrdenDeCompra;
import facade.OrdenDeCompraFacade;
import includes.Comunes;
import includes.ModeloTablaNoEditable;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author franco
 */
public class DiagListaOrdenDeCompra extends javax.swing.JDialog {

    private OrdenDeCompra ordenDeCompraSeleccionada;
    private ModeloTablaNoEditable modeloTablaOrdenes;
    private Usuario usuario;
    private Sucursal sucursal;

    /**
     * Creates new form DiagListaOrdenDeCompra
     */
    public DiagListaOrdenDeCompra(java.awt.Frame parent, boolean modal, Usuario usuario, Sucursal sucursal) {
        super(parent, modal);
        this.usuario = usuario;
        this.sucursal = sucursal;
        initComponents();
        inicializarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrdenesDeCompra = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(DiagListaOrdenDeCompra.class, "DiagListaOrdenDeCompra.jPanel5.border.border.title")))); // NOI18N

        tblOrdenesDeCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblOrdenesDeCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdenesDeCompraMouseClicked(evt);
            }
        });
        tblOrdenesDeCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblOrdenesDeCompraKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblOrdenesDeCompra);

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/add.png"))); // NOI18N
        btnAgregar.setText(org.openide.util.NbBundle.getMessage(DiagListaOrdenDeCompra.class, "DiagListaOrdenDeCompra.btnAgregar.text")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete.png"))); // NOI18N
        btnEliminar.setText(org.openide.util.NbBundle.getMessage(DiagListaOrdenDeCompra.class, "DiagListaOrdenDeCompra.btnEliminar.text")); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit.png"))); // NOI18N
        btnModificar.setText(org.openide.util.NbBundle.getMessage(DiagListaOrdenDeCompra.class, "DiagListaOrdenDeCompra.btnModificar.text")); // NOI18N
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgregar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(btnModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar)
                .addGap(30, 30, 30))
        );

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/back.png"))); // NOI18N
        btnSalir.setText(org.openide.util.NbBundle.getMessage(DiagListaOrdenDeCompra.class, "DiagListaOrdenDeCompra.btnSalir.text")); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnSalir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrdenesDeCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdenesDeCompraMouseClicked
        if (evt.getClickCount() == 2) {
            seleccionarOrdenDeCompra();// aqui va a ir el modificar
        }
        if (evt.getClickCount() == 1) {
            seleccionarOrdenDeCompra();
        }
    }//GEN-LAST:event_tblOrdenesDeCompraMouseClicked

    private void tblOrdenesDeCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblOrdenesDeCompraKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            seleccionarOrdenDeCompra();
        }
    }//GEN-LAST:event_tblOrdenesDeCompraKeyPressed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        modificarOrdenDeCompra();
    }//GEN-LAST:event_btnModificarActionPerformed
    private void seleccionarOrdenDeCompra() {
        if (tblOrdenesDeCompra.getSelectedRow() != -1) {
            ordenDeCompraSeleccionada = OrdenDeCompraFacade.getInstance().buscar((Long) tblOrdenesDeCompra.getValueAt(tblOrdenesDeCompra.getSelectedRow(), 0));
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblOrdenesDeCompra;
    // End of variables declaration//GEN-END:variables

    private void inicializarComponentes() {
        List<OrdenDeCompra> ordenDeCompras = OrdenDeCompraFacade.getInstance().listaOrdenDeComprasDescendente();
        cargarTablaOrdenes(ordenDeCompras);
        tblOrdenesDeCompra.requestFocus();
    }

    private void cargarTablaOrdenes(List<OrdenDeCompra> ordenDeCompras) {
        modeloTablaOrdenes = new ModeloTablaNoEditable();
        cargarEncabezadosTablaOrdenes(modeloTablaOrdenes);
        configurarTabla(tblOrdenesDeCompra);
        try {
            cargarOrdenes(ordenDeCompras);
        } catch (Exception ex) {
            Logger.getLogger(FrVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarEncabezadosTablaOrdenes(ModeloTablaNoEditable modeloTablaOrdenes) {
        modeloTablaOrdenes.addColumn("Id");
        modeloTablaOrdenes.addColumn("Número");
        modeloTablaOrdenes.addColumn("Cliente");
        modeloTablaOrdenes.addColumn("DNI/CUIT");
        modeloTablaOrdenes.addColumn("Fecha");
        modeloTablaOrdenes.addColumn("Monto");
        tblOrdenesDeCompra.setModel(modeloTablaOrdenes);
    }

    private void cargarOrdenes(List<OrdenDeCompra> ordenDeCompras) {
        try {
            modeloTablaOrdenes = new ModeloTablaNoEditable();
            cargarEncabezadosTablaOrdenes(modeloTablaOrdenes);
            for (OrdenDeCompra ventaArt : ordenDeCompras) {
                cargarOrdenes(ventaArt);
            }
            tblOrdenesDeCompra.setModel(modeloTablaOrdenes);
            Comunes.setOcultarColumnasJTable(tblOrdenesDeCompra, 0);
        } catch (Exception ex) {
            Logger.getLogger(FrVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void cargarOrdenes(OrdenDeCompra ordenDeCompra) {

        Object[] fila = new Object[6];
        fila[0] = ordenDeCompra.getId();
        fila[1] = ordenDeCompra.getNumeroOrden();
        try {
            fila[2] = ordenDeCompra.getCliente().toString();
        } catch (Exception e) {
        }
        try {
            if (ordenDeCompra.getCliente().getClass() == Persona.class) {
                fila[3] = ((Persona) ordenDeCompra.getCliente()).getDocumentoIdentidad().getNumero();
            } else {
                fila[3] = ((Organismo) ordenDeCompra.getCliente()).getCUIT();
            }
        } catch (Exception e) {
        }
        try {
            fila[4] = new SimpleDateFormat("dd/MM/yyyy").format(ordenDeCompra.getFecha());
        } catch (Exception e) {
        }
        try {
            fila[5] = ordenDeCompra.getMonto().toString();
        } catch (Exception e) {
        }
        modeloTablaOrdenes.addRow(fila);
    }

    private void configurarTabla(JTable tbl) {
        JViewport scroll = (JViewport) tbl.getParent();
        int ancho = scroll.getWidth();
        int anchoColumna = 0;
        TableColumnModel modeloColumna = tbl.getColumnModel();
        TableColumn columnaTabla;
        for (int i = 0; i < tbl.getColumnCount(); i++) {
            columnaTabla = modeloColumna.getColumn(i);
            switch (i) {
                case 0:
                    anchoColumna = 1 / 100;
                    break;
                case 1:
                    anchoColumna = (20 * ancho) / 100;
                    break;
                case 2:
                case 3:
                case 4:
                case 5:
                case 6:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                    anchoColumna = (5 * ancho) / 100;
                    break;
            }
            columnaTabla.setPreferredWidth(anchoColumna);
            tbl.setColumnModel(modeloColumna);
        }
        tbl.getTableHeader().setBackground(java.awt.Color.WHITE);
        tbl.getTableHeader().setForeground(Color.BLACK);
        tbl.getTableHeader().setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 14));
        //Si le queremos cambiar el tamaño a la tablita
        tbl.setFont(new java.awt.Font("Dialog",
                java.awt.Font.PLAIN, 14));
    }

    private void agregar() {
        DiagOrdenesDeCompra diagOrdenesDeCompra = new DiagOrdenesDeCompra(null, true, usuario, sucursal,"Alta");
        diagOrdenesDeCompra.setLocation(Comunes.centrarDialog(diagOrdenesDeCompra));
        diagOrdenesDeCompra.setVisible(true);
        inicializarComponentes();
    }

    private void eliminar() {
        if (ordenDeCompraSeleccionada != null) {
            OrdenDeCompraFacade.getInstance().eliminar(ordenDeCompraSeleccionada.getId());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una orden de compra");
            tblOrdenesDeCompra.requestFocus();
        }
        inicializarComponentes();
    }

    private void modificarOrdenDeCompra() {
        if (tblOrdenesDeCompra.getSelectedRow() != -1) {
            ordenDeCompraSeleccionada = OrdenDeCompraFacade.getInstance().buscar((Long) tblOrdenesDeCompra.getValueAt(tblOrdenesDeCompra.getSelectedRow(), 0));
            DiagOrdenesDeCompra diagOrdenesDeCompra=new DiagOrdenesDeCompra(null, true, usuario, sucursal,"Modificación",ordenDeCompraSeleccionada);
            diagOrdenesDeCompra.setLocation(Comunes.centrarDialog(diagOrdenesDeCompra));
            diagOrdenesDeCompra.setVisible(true);
            inicializarComponentes();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una orden de compra");
        }
    }

}
